import { useState } from 'react'
import Head from 'next/head'

export default function AboutPage() {
  const [url, setUrl] = useState('')

  const handleSubmit = () => {
    const input = document.querySelector('input') as HTMLInputElement
    const name = input.value

    fetch('/api/generate/pdf', {
      method: 'POST',
      body: JSON.stringify({ name }),
      headers: {
        Accept: 'application/pdf'
      }
    })
      .then((response) => {
        return response.blob()
      })
      .then((blob) => {
        const newUrl = URL.createObjectURL(blob)
        setUrl(newUrl)
      })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <input name="name" />
        <button type="button" onClick={handleSubmit}>
          Submit name
        </button>
        {url && <embed style={{ width: '100vw', height: '100vh' }} src={url} />}
      </main>
    </div>
  )
}
