// flow-typed signature: b6f0e8c15c0bf4dcb2e5647dbbfd50e9
// flow-typed version: <<STUB>>/open-browser-webpack-plugin_v0.0.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open-browser-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open-browser-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'open-browser-webpack-plugin/fixtures/debug' {
  declare module.exports: any;
}

declare module 'open-browser-webpack-plugin/fixtures/lib/entry' {
  declare module.exports: any;
}

declare module 'open-browser-webpack-plugin/fixtures/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'open-browser-webpack-plugin/fixtures/debug.js' {
  declare module.exports: $Exports<'open-browser-webpack-plugin/fixtures/debug'>;
}
declare module 'open-browser-webpack-plugin/fixtures/lib/entry.js' {
  declare module.exports: $Exports<'open-browser-webpack-plugin/fixtures/lib/entry'>;
}
declare module 'open-browser-webpack-plugin/fixtures/webpack.config.js' {
  declare module.exports: $Exports<'open-browser-webpack-plugin/fixtures/webpack.config'>;
}
declare module 'open-browser-webpack-plugin/index' {
  declare module.exports: $Exports<'open-browser-webpack-plugin'>;
}
declare module 'open-browser-webpack-plugin/index.js' {
  declare module.exports: $Exports<'open-browser-webpack-plugin'>;
}
