// flow-typed signature: 0df6d74f899daaa2945f5b1b5514bea9
// flow-typed version: <<STUB>>/react-pdf_v^1.6.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pdf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pdf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pdf/es5/react-pdf' {
  declare module.exports: any;
}

declare module 'react-pdf/sample/sample' {
  declare module.exports: any;
}

declare module 'react-pdf/src-sample/sample' {
  declare module.exports: any;
}

declare module 'react-pdf/src-test/test' {
  declare module.exports: any;
}

declare module 'react-pdf/src/react-pdf' {
  declare module.exports: any;
}

declare module 'react-pdf/test/test' {
  declare module.exports: any;
}

declare module 'react-pdf/webpack.config.sample' {
  declare module.exports: any;
}

declare module 'react-pdf/webpack.config.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pdf/es5/react-pdf.js' {
  declare module.exports: $Exports<'react-pdf/es5/react-pdf'>;
}
declare module 'react-pdf/sample/sample.js' {
  declare module.exports: $Exports<'react-pdf/sample/sample'>;
}
declare module 'react-pdf/src-sample/sample.jsx' {
  declare module.exports: $Exports<'react-pdf/src-sample/sample'>;
}
declare module 'react-pdf/src-test/test.jsx' {
  declare module.exports: $Exports<'react-pdf/src-test/test'>;
}
declare module 'react-pdf/src/react-pdf.jsx' {
  declare module.exports: $Exports<'react-pdf/src/react-pdf'>;
}
declare module 'react-pdf/test/test.js' {
  declare module.exports: $Exports<'react-pdf/test/test'>;
}
declare module 'react-pdf/webpack.config.sample.js' {
  declare module.exports: $Exports<'react-pdf/webpack.config.sample'>;
}
declare module 'react-pdf/webpack.config.test.js' {
  declare module.exports: $Exports<'react-pdf/webpack.config.test'>;
}
