// flow-typed signature: 15834282046d626020526236d5e6dc6a
// flow-typed version: <<STUB>>/react-router-transition_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-transition/lib/react-router-transition' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/AnimatedRoute' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/AnimatedSwitch' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/ensureSpring' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/index' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/RouteTransition' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/spring' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-transition/lib/react-router-transition.js' {
  declare module.exports: $Exports<'react-router-transition/lib/react-router-transition'>;
}
declare module 'react-router-transition/src/AnimatedRoute.js' {
  declare module.exports: $Exports<'react-router-transition/src/AnimatedRoute'>;
}
declare module 'react-router-transition/src/AnimatedSwitch.js' {
  declare module.exports: $Exports<'react-router-transition/src/AnimatedSwitch'>;
}
declare module 'react-router-transition/src/ensureSpring.js' {
  declare module.exports: $Exports<'react-router-transition/src/ensureSpring'>;
}
declare module 'react-router-transition/src/index.js' {
  declare module.exports: $Exports<'react-router-transition/src/index'>;
}
declare module 'react-router-transition/src/RouteTransition.js' {
  declare module.exports: $Exports<'react-router-transition/src/RouteTransition'>;
}
declare module 'react-router-transition/src/spring.js' {
  declare module.exports: $Exports<'react-router-transition/src/spring'>;
}
