// flow-typed signature: 78a4c3311b74fd33ddea4bcaea589bb7
// flow-typed version: <<STUB>>/redux-form_v6.6.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-form/dist/redux-form' {
  declare module.exports: any;
}

declare module 'redux-form/dist/redux-form.min' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/actions.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/addExpectations' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/asyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/createFieldArrayProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/createFieldProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/defaultShouldAsyncValidate.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/defaultShouldValidate.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/deleteInWithCleanUp.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/Field.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/FieldArray.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/fieldKeys.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/Fields.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/Form.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/FormSection.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/formValueSelector.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/generateFields.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/generateValidator.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/handleSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/hasError.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/immutable.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayInsert.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayMove.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayPop.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayPush.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayRemove.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayRemoveAll.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayShift.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arraySplice.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arraySwap.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.arrayUnshift.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.autofill.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.blur.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.change.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.clearAsyncError.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.clearSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.clearSubmitErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.destroy.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.focus.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.initialize.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.plugin.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.registerField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.reset.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.setSubmitFailed.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.setSubmitSuceeded.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.startAsyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.startSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.stopAsyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.stopSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.submit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.touch.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.unregisterField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.untouch.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.updateSyncErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reducer.updateSyncWarnings.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/reduxForm.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/setup' {
  declare module.exports: any;
}

declare module 'redux-form/es/__tests__/values.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/actions' {
  declare module.exports: any;
}

declare module 'redux-form/es/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-form/es/asyncValidation' {
  declare module.exports: any;
}

declare module 'redux-form/es/ConnectedField' {
  declare module.exports: any;
}

declare module 'redux-form/es/ConnectedFieldArray' {
  declare module.exports: any;
}

declare module 'redux-form/es/ConnectedFields' {
  declare module.exports: any;
}

declare module 'redux-form/es/createAll' {
  declare module.exports: any;
}

declare module 'redux-form/es/createFieldArrayProps' {
  declare module.exports: any;
}

declare module 'redux-form/es/createFieldProps' {
  declare module.exports: any;
}

declare module 'redux-form/es/defaultShouldAsyncValidate' {
  declare module.exports: any;
}

declare module 'redux-form/es/defaultShouldValidate' {
  declare module.exports: any;
}

declare module 'redux-form/es/deleteInWithCleanUp' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/__tests__/getValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/__tests__/isEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/__tests__/onChangeValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/__tests__/silenceEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/__tests__/silenceEvents.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/getValue' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/isEvent' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/onChangeValue' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/silenceEvent' {
  declare module.exports: any;
}

declare module 'redux-form/es/events/silenceEvents' {
  declare module.exports: any;
}

declare module 'redux-form/es/Field' {
  declare module.exports: any;
}

declare module 'redux-form/es/FieldArray' {
  declare module.exports: any;
}

declare module 'redux-form/es/fieldKeys' {
  declare module.exports: any;
}

declare module 'redux-form/es/Fields' {
  declare module.exports: any;
}

declare module 'redux-form/es/Form' {
  declare module.exports: any;
}

declare module 'redux-form/es/FormSection' {
  declare module.exports: any;
}

declare module 'redux-form/es/formValueSelector' {
  declare module.exports: any;
}

declare module 'redux-form/es/generateFields' {
  declare module.exports: any;
}

declare module 'redux-form/es/generateValidator' {
  declare module.exports: any;
}

declare module 'redux-form/es/handleSubmit' {
  declare module.exports: any;
}

declare module 'redux-form/es/hasError' {
  declare module.exports: any;
}

declare module 'redux-form/es/immutable' {
  declare module.exports: any;
}

declare module 'redux-form/es/index' {
  declare module.exports: any;
}

declare module 'redux-form/es/isChecked' {
  declare module.exports: any;
}

declare module 'redux-form/es/isReactNative' {
  declare module.exports: any;
}

declare module 'redux-form/es/propTypes' {
  declare module.exports: any;
}

declare module 'redux-form/es/reducer' {
  declare module.exports: any;
}

declare module 'redux-form/es/reduxForm' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/getFormAsyncErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/getFormInitialValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/getFormNames.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/getFormSubmitErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/getFormSyncErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/getFormSyncWarnings.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/getFormValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/hasSubmitFailed.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/hasSubmitSucceeded.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/isDirty.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/isInvalid.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/isPristine.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/isSubmitting.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/__tests__/isValid.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/getFormAsyncErrors' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/getFormInitialValues' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/getFormNames' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/getFormSubmitErrors' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/getFormSyncErrors' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/getFormSyncWarnings' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/getFormValues' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/hasSubmitFailed' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/hasSubmitSucceeded' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/isDirty' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/isInvalid' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/isPristine' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/isSubmitting' {
  declare module.exports: any;
}

declare module 'redux-form/es/selectors/isValid' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/__tests__/deepEqual.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/__tests__/keys.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/__tests__/setIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/__tests__/splice.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/deepEqual' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/expectations' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/index' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/keys' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/setIn' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/immutable/splice' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/__tests__/deepEqual.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/__tests__/deleteIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/__tests__/getIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/__tests__/keys.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/__tests__/setIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/__tests__/splice.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/deepEqual' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/deleteIn' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/expectations' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/getIn' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/index' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/keys' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/setIn' {
  declare module.exports: any;
}

declare module 'redux-form/es/structure/plain/splice' {
  declare module.exports: any;
}

declare module 'redux-form/es/SubmissionError' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/__tests__/eventMocks.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/__tests__/getDisplayName.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/__tests__/prefixName.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/__tests__/shallowCompare.spec' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/eventConsts' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/eventMocks' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/getDisplayName' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/prefixName' {
  declare module.exports: any;
}

declare module 'redux-form/es/util/shallowCompare' {
  declare module.exports: any;
}

declare module 'redux-form/es/values' {
  declare module.exports: any;
}

declare module 'redux-form/immutable' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/actions.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/addExpectations' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/asyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/createFieldArrayProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/createFieldProps.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/defaultShouldAsyncValidate.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/defaultShouldValidate.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/deleteInWithCleanUp.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/Field.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/FieldArray.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/fieldKeys.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/Fields.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/Form.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/FormSection.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/formValueSelector.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/generateFields.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/generateValidator.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/handleSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/hasError.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/immutable.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayInsert.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayMove.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayPop.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayPush.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayRemove.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayRemoveAll.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayShift.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arraySplice.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arraySwap.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.arrayUnshift.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.autofill.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.blur.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.change.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.clearAsyncError.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.clearSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.clearSubmitErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.destroy.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.focus.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.initialize.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.plugin.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.registerField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.reset.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.setSubmitFailed.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.setSubmitSuceeded.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.startAsyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.startSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.stopAsyncValidation.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.stopSubmit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.submit.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.touch.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.unregisterField.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.untouch.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.updateSyncErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reducer.updateSyncWarnings.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/reduxForm.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/setup' {
  declare module.exports: any;
}

declare module 'redux-form/lib/__tests__/values.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-form/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-form/lib/asyncValidation' {
  declare module.exports: any;
}

declare module 'redux-form/lib/ConnectedField' {
  declare module.exports: any;
}

declare module 'redux-form/lib/ConnectedFieldArray' {
  declare module.exports: any;
}

declare module 'redux-form/lib/ConnectedFields' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createAll' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createFieldArrayProps' {
  declare module.exports: any;
}

declare module 'redux-form/lib/createFieldProps' {
  declare module.exports: any;
}

declare module 'redux-form/lib/defaultShouldAsyncValidate' {
  declare module.exports: any;
}

declare module 'redux-form/lib/defaultShouldValidate' {
  declare module.exports: any;
}

declare module 'redux-form/lib/deleteInWithCleanUp' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/getValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/isEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/onChangeValue.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/silenceEvent.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/__tests__/silenceEvents.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/getValue' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/isEvent' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/onChangeValue' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/silenceEvent' {
  declare module.exports: any;
}

declare module 'redux-form/lib/events/silenceEvents' {
  declare module.exports: any;
}

declare module 'redux-form/lib/Field' {
  declare module.exports: any;
}

declare module 'redux-form/lib/FieldArray' {
  declare module.exports: any;
}

declare module 'redux-form/lib/fieldKeys' {
  declare module.exports: any;
}

declare module 'redux-form/lib/Fields' {
  declare module.exports: any;
}

declare module 'redux-form/lib/Form' {
  declare module.exports: any;
}

declare module 'redux-form/lib/FormSection' {
  declare module.exports: any;
}

declare module 'redux-form/lib/formValueSelector' {
  declare module.exports: any;
}

declare module 'redux-form/lib/generateFields' {
  declare module.exports: any;
}

declare module 'redux-form/lib/generateValidator' {
  declare module.exports: any;
}

declare module 'redux-form/lib/handleSubmit' {
  declare module.exports: any;
}

declare module 'redux-form/lib/hasError' {
  declare module.exports: any;
}

declare module 'redux-form/lib/immutable' {
  declare module.exports: any;
}

declare module 'redux-form/lib/index' {
  declare module.exports: any;
}

declare module 'redux-form/lib/isChecked' {
  declare module.exports: any;
}

declare module 'redux-form/lib/isReactNative' {
  declare module.exports: any;
}

declare module 'redux-form/lib/propTypes' {
  declare module.exports: any;
}

declare module 'redux-form/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-form/lib/reduxForm' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/getFormAsyncErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/getFormInitialValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/getFormNames.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/getFormSubmitErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/getFormSyncErrors.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/getFormSyncWarnings.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/getFormValues.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/hasSubmitFailed.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/hasSubmitSucceeded.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/isDirty.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/isInvalid.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/isPristine.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/isSubmitting.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/__tests__/isValid.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/getFormAsyncErrors' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/getFormInitialValues' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/getFormNames' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/getFormSubmitErrors' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/getFormSyncErrors' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/getFormSyncWarnings' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/getFormValues' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/hasSubmitFailed' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/hasSubmitSucceeded' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/isDirty' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/isInvalid' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/isPristine' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/isSubmitting' {
  declare module.exports: any;
}

declare module 'redux-form/lib/selectors/isValid' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/__tests__/deepEqual.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/__tests__/keys.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/__tests__/setIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/__tests__/splice.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/deepEqual' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/expectations' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/index' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/keys' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/setIn' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/immutable/splice' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/__tests__/deepEqual.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/__tests__/deleteIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/__tests__/getIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/__tests__/keys.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/__tests__/setIn.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/__tests__/splice.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/deepEqual' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/deleteIn' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/expectations' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/getIn' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/index' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/keys' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/setIn' {
  declare module.exports: any;
}

declare module 'redux-form/lib/structure/plain/splice' {
  declare module.exports: any;
}

declare module 'redux-form/lib/SubmissionError' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/__tests__/eventMocks.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/__tests__/getDisplayName.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/__tests__/prefixName.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/__tests__/shallowCompare.spec' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/eventConsts' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/eventMocks' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/getDisplayName' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/prefixName' {
  declare module.exports: any;
}

declare module 'redux-form/lib/util/shallowCompare' {
  declare module.exports: any;
}

declare module 'redux-form/lib/values' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-form/dist/redux-form.js' {
  declare module.exports: $Exports<'redux-form/dist/redux-form'>;
}
declare module 'redux-form/dist/redux-form.min.js' {
  declare module.exports: $Exports<'redux-form/dist/redux-form.min'>;
}
declare module 'redux-form/es/__tests__/actions.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/actions.spec'>;
}
declare module 'redux-form/es/__tests__/addExpectations.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/addExpectations'>;
}
declare module 'redux-form/es/__tests__/asyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/asyncValidation.spec'>;
}
declare module 'redux-form/es/__tests__/createFieldArrayProps.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/createFieldArrayProps.spec'>;
}
declare module 'redux-form/es/__tests__/createFieldProps.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/createFieldProps.spec'>;
}
declare module 'redux-form/es/__tests__/defaultShouldAsyncValidate.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/defaultShouldAsyncValidate.spec'>;
}
declare module 'redux-form/es/__tests__/defaultShouldValidate.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/defaultShouldValidate.spec'>;
}
declare module 'redux-form/es/__tests__/deleteInWithCleanUp.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/deleteInWithCleanUp.spec'>;
}
declare module 'redux-form/es/__tests__/Field.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/Field.spec'>;
}
declare module 'redux-form/es/__tests__/FieldArray.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/FieldArray.spec'>;
}
declare module 'redux-form/es/__tests__/fieldKeys.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/fieldKeys.spec'>;
}
declare module 'redux-form/es/__tests__/Fields.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/Fields.spec'>;
}
declare module 'redux-form/es/__tests__/Form.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/Form.spec'>;
}
declare module 'redux-form/es/__tests__/FormSection.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/FormSection.spec'>;
}
declare module 'redux-form/es/__tests__/formValueSelector.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/formValueSelector.spec'>;
}
declare module 'redux-form/es/__tests__/generateFields.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/generateFields.spec'>;
}
declare module 'redux-form/es/__tests__/generateValidator.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/generateValidator.spec'>;
}
declare module 'redux-form/es/__tests__/handleSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/handleSubmit.spec'>;
}
declare module 'redux-form/es/__tests__/hasError.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/hasError.spec'>;
}
declare module 'redux-form/es/__tests__/immutable.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/immutable.spec'>;
}
declare module 'redux-form/es/__tests__/index.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/index.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayInsert.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayInsert.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayMove.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayMove.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayPop.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayPop.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayPush.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayPush.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayRemove.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayRemove.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayRemoveAll.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayRemoveAll.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayShift.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayShift.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arraySplice.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arraySplice.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arraySwap.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arraySwap.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.arrayUnshift.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.arrayUnshift.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.autofill.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.autofill.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.blur.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.blur.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.change.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.change.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.clearAsyncError.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.clearAsyncError.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.clearSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.clearSubmit.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.clearSubmitErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.clearSubmitErrors.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.destroy.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.destroy.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.focus.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.focus.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.initialize.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.initialize.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.plugin.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.plugin.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.registerField.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.registerField.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.reset.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.reset.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.setSubmitFailed.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.setSubmitFailed.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.setSubmitSuceeded.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.setSubmitSuceeded.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.startAsyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.startAsyncValidation.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.startSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.startSubmit.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.stopAsyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.stopAsyncValidation.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.stopSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.stopSubmit.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.submit.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.submit.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.touch.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.touch.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.unregisterField.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.unregisterField.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.untouch.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.untouch.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.updateSyncErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.updateSyncErrors.spec'>;
}
declare module 'redux-form/es/__tests__/reducer.updateSyncWarnings.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reducer.updateSyncWarnings.spec'>;
}
declare module 'redux-form/es/__tests__/reduxForm.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/reduxForm.spec'>;
}
declare module 'redux-form/es/__tests__/setup.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/setup'>;
}
declare module 'redux-form/es/__tests__/values.spec.js' {
  declare module.exports: $Exports<'redux-form/es/__tests__/values.spec'>;
}
declare module 'redux-form/es/actions.js' {
  declare module.exports: $Exports<'redux-form/es/actions'>;
}
declare module 'redux-form/es/actionTypes.js' {
  declare module.exports: $Exports<'redux-form/es/actionTypes'>;
}
declare module 'redux-form/es/asyncValidation.js' {
  declare module.exports: $Exports<'redux-form/es/asyncValidation'>;
}
declare module 'redux-form/es/ConnectedField.js' {
  declare module.exports: $Exports<'redux-form/es/ConnectedField'>;
}
declare module 'redux-form/es/ConnectedFieldArray.js' {
  declare module.exports: $Exports<'redux-form/es/ConnectedFieldArray'>;
}
declare module 'redux-form/es/ConnectedFields.js' {
  declare module.exports: $Exports<'redux-form/es/ConnectedFields'>;
}
declare module 'redux-form/es/createAll.js' {
  declare module.exports: $Exports<'redux-form/es/createAll'>;
}
declare module 'redux-form/es/createFieldArrayProps.js' {
  declare module.exports: $Exports<'redux-form/es/createFieldArrayProps'>;
}
declare module 'redux-form/es/createFieldProps.js' {
  declare module.exports: $Exports<'redux-form/es/createFieldProps'>;
}
declare module 'redux-form/es/defaultShouldAsyncValidate.js' {
  declare module.exports: $Exports<'redux-form/es/defaultShouldAsyncValidate'>;
}
declare module 'redux-form/es/defaultShouldValidate.js' {
  declare module.exports: $Exports<'redux-form/es/defaultShouldValidate'>;
}
declare module 'redux-form/es/deleteInWithCleanUp.js' {
  declare module.exports: $Exports<'redux-form/es/deleteInWithCleanUp'>;
}
declare module 'redux-form/es/events/__tests__/getValue.spec.js' {
  declare module.exports: $Exports<'redux-form/es/events/__tests__/getValue.spec'>;
}
declare module 'redux-form/es/events/__tests__/isEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/es/events/__tests__/isEvent.spec'>;
}
declare module 'redux-form/es/events/__tests__/onChangeValue.spec.js' {
  declare module.exports: $Exports<'redux-form/es/events/__tests__/onChangeValue.spec'>;
}
declare module 'redux-form/es/events/__tests__/silenceEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/es/events/__tests__/silenceEvent.spec'>;
}
declare module 'redux-form/es/events/__tests__/silenceEvents.spec.js' {
  declare module.exports: $Exports<'redux-form/es/events/__tests__/silenceEvents.spec'>;
}
declare module 'redux-form/es/events/getValue.js' {
  declare module.exports: $Exports<'redux-form/es/events/getValue'>;
}
declare module 'redux-form/es/events/isEvent.js' {
  declare module.exports: $Exports<'redux-form/es/events/isEvent'>;
}
declare module 'redux-form/es/events/onChangeValue.js' {
  declare module.exports: $Exports<'redux-form/es/events/onChangeValue'>;
}
declare module 'redux-form/es/events/silenceEvent.js' {
  declare module.exports: $Exports<'redux-form/es/events/silenceEvent'>;
}
declare module 'redux-form/es/events/silenceEvents.js' {
  declare module.exports: $Exports<'redux-form/es/events/silenceEvents'>;
}
declare module 'redux-form/es/Field.js' {
  declare module.exports: $Exports<'redux-form/es/Field'>;
}
declare module 'redux-form/es/FieldArray.js' {
  declare module.exports: $Exports<'redux-form/es/FieldArray'>;
}
declare module 'redux-form/es/fieldKeys.js' {
  declare module.exports: $Exports<'redux-form/es/fieldKeys'>;
}
declare module 'redux-form/es/Fields.js' {
  declare module.exports: $Exports<'redux-form/es/Fields'>;
}
declare module 'redux-form/es/Form.js' {
  declare module.exports: $Exports<'redux-form/es/Form'>;
}
declare module 'redux-form/es/FormSection.js' {
  declare module.exports: $Exports<'redux-form/es/FormSection'>;
}
declare module 'redux-form/es/formValueSelector.js' {
  declare module.exports: $Exports<'redux-form/es/formValueSelector'>;
}
declare module 'redux-form/es/generateFields.js' {
  declare module.exports: $Exports<'redux-form/es/generateFields'>;
}
declare module 'redux-form/es/generateValidator.js' {
  declare module.exports: $Exports<'redux-form/es/generateValidator'>;
}
declare module 'redux-form/es/handleSubmit.js' {
  declare module.exports: $Exports<'redux-form/es/handleSubmit'>;
}
declare module 'redux-form/es/hasError.js' {
  declare module.exports: $Exports<'redux-form/es/hasError'>;
}
declare module 'redux-form/es/immutable.js' {
  declare module.exports: $Exports<'redux-form/es/immutable'>;
}
declare module 'redux-form/es/index.js' {
  declare module.exports: $Exports<'redux-form/es/index'>;
}
declare module 'redux-form/es/isChecked.js' {
  declare module.exports: $Exports<'redux-form/es/isChecked'>;
}
declare module 'redux-form/es/isReactNative.js' {
  declare module.exports: $Exports<'redux-form/es/isReactNative'>;
}
declare module 'redux-form/es/propTypes.js' {
  declare module.exports: $Exports<'redux-form/es/propTypes'>;
}
declare module 'redux-form/es/reducer.js' {
  declare module.exports: $Exports<'redux-form/es/reducer'>;
}
declare module 'redux-form/es/reduxForm.js' {
  declare module.exports: $Exports<'redux-form/es/reduxForm'>;
}
declare module 'redux-form/es/selectors/__tests__/getFormAsyncErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/getFormAsyncErrors.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/getFormInitialValues.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/getFormInitialValues.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/getFormNames.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/getFormNames.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/getFormSubmitErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/getFormSubmitErrors.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/getFormSyncErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/getFormSyncErrors.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/getFormSyncWarnings.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/getFormSyncWarnings.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/getFormValues.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/getFormValues.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/hasSubmitFailed.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/hasSubmitFailed.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/hasSubmitSucceeded.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/hasSubmitSucceeded.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/isDirty.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/isDirty.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/isInvalid.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/isInvalid.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/isPristine.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/isPristine.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/isSubmitting.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/isSubmitting.spec'>;
}
declare module 'redux-form/es/selectors/__tests__/isValid.spec.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/__tests__/isValid.spec'>;
}
declare module 'redux-form/es/selectors/getFormAsyncErrors.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/getFormAsyncErrors'>;
}
declare module 'redux-form/es/selectors/getFormInitialValues.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/getFormInitialValues'>;
}
declare module 'redux-form/es/selectors/getFormNames.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/getFormNames'>;
}
declare module 'redux-form/es/selectors/getFormSubmitErrors.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/getFormSubmitErrors'>;
}
declare module 'redux-form/es/selectors/getFormSyncErrors.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/getFormSyncErrors'>;
}
declare module 'redux-form/es/selectors/getFormSyncWarnings.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/getFormSyncWarnings'>;
}
declare module 'redux-form/es/selectors/getFormValues.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/getFormValues'>;
}
declare module 'redux-form/es/selectors/hasSubmitFailed.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/hasSubmitFailed'>;
}
declare module 'redux-form/es/selectors/hasSubmitSucceeded.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/hasSubmitSucceeded'>;
}
declare module 'redux-form/es/selectors/isDirty.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/isDirty'>;
}
declare module 'redux-form/es/selectors/isInvalid.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/isInvalid'>;
}
declare module 'redux-form/es/selectors/isPristine.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/isPristine'>;
}
declare module 'redux-form/es/selectors/isSubmitting.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/isSubmitting'>;
}
declare module 'redux-form/es/selectors/isValid.js' {
  declare module.exports: $Exports<'redux-form/es/selectors/isValid'>;
}
declare module 'redux-form/es/structure/immutable/__tests__/deepEqual.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/__tests__/deepEqual.spec'>;
}
declare module 'redux-form/es/structure/immutable/__tests__/keys.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/__tests__/keys.spec'>;
}
declare module 'redux-form/es/structure/immutable/__tests__/setIn.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/__tests__/setIn.spec'>;
}
declare module 'redux-form/es/structure/immutable/__tests__/splice.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/__tests__/splice.spec'>;
}
declare module 'redux-form/es/structure/immutable/deepEqual.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/deepEqual'>;
}
declare module 'redux-form/es/structure/immutable/expectations.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/expectations'>;
}
declare module 'redux-form/es/structure/immutable/index.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/index'>;
}
declare module 'redux-form/es/structure/immutable/keys.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/keys'>;
}
declare module 'redux-form/es/structure/immutable/setIn.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/setIn'>;
}
declare module 'redux-form/es/structure/immutable/splice.js' {
  declare module.exports: $Exports<'redux-form/es/structure/immutable/splice'>;
}
declare module 'redux-form/es/structure/plain/__tests__/deepEqual.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/__tests__/deepEqual.spec'>;
}
declare module 'redux-form/es/structure/plain/__tests__/deleteIn.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/__tests__/deleteIn.spec'>;
}
declare module 'redux-form/es/structure/plain/__tests__/getIn.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/__tests__/getIn.spec'>;
}
declare module 'redux-form/es/structure/plain/__tests__/keys.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/__tests__/keys.spec'>;
}
declare module 'redux-form/es/structure/plain/__tests__/setIn.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/__tests__/setIn.spec'>;
}
declare module 'redux-form/es/structure/plain/__tests__/splice.spec.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/__tests__/splice.spec'>;
}
declare module 'redux-form/es/structure/plain/deepEqual.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/deepEqual'>;
}
declare module 'redux-form/es/structure/plain/deleteIn.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/deleteIn'>;
}
declare module 'redux-form/es/structure/plain/expectations.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/expectations'>;
}
declare module 'redux-form/es/structure/plain/getIn.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/getIn'>;
}
declare module 'redux-form/es/structure/plain/index.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/index'>;
}
declare module 'redux-form/es/structure/plain/keys.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/keys'>;
}
declare module 'redux-form/es/structure/plain/setIn.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/setIn'>;
}
declare module 'redux-form/es/structure/plain/splice.js' {
  declare module.exports: $Exports<'redux-form/es/structure/plain/splice'>;
}
declare module 'redux-form/es/SubmissionError.js' {
  declare module.exports: $Exports<'redux-form/es/SubmissionError'>;
}
declare module 'redux-form/es/util/__tests__/eventMocks.spec.js' {
  declare module.exports: $Exports<'redux-form/es/util/__tests__/eventMocks.spec'>;
}
declare module 'redux-form/es/util/__tests__/getDisplayName.spec.js' {
  declare module.exports: $Exports<'redux-form/es/util/__tests__/getDisplayName.spec'>;
}
declare module 'redux-form/es/util/__tests__/prefixName.spec.js' {
  declare module.exports: $Exports<'redux-form/es/util/__tests__/prefixName.spec'>;
}
declare module 'redux-form/es/util/__tests__/shallowCompare.spec.js' {
  declare module.exports: $Exports<'redux-form/es/util/__tests__/shallowCompare.spec'>;
}
declare module 'redux-form/es/util/eventConsts.js' {
  declare module.exports: $Exports<'redux-form/es/util/eventConsts'>;
}
declare module 'redux-form/es/util/eventMocks.js' {
  declare module.exports: $Exports<'redux-form/es/util/eventMocks'>;
}
declare module 'redux-form/es/util/getDisplayName.js' {
  declare module.exports: $Exports<'redux-form/es/util/getDisplayName'>;
}
declare module 'redux-form/es/util/prefixName.js' {
  declare module.exports: $Exports<'redux-form/es/util/prefixName'>;
}
declare module 'redux-form/es/util/shallowCompare.js' {
  declare module.exports: $Exports<'redux-form/es/util/shallowCompare'>;
}
declare module 'redux-form/es/values.js' {
  declare module.exports: $Exports<'redux-form/es/values'>;
}
declare module 'redux-form/immutable.js' {
  declare module.exports: $Exports<'redux-form/immutable'>;
}
declare module 'redux-form/lib/__tests__/actions.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/actions.spec'>;
}
declare module 'redux-form/lib/__tests__/addExpectations.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/addExpectations'>;
}
declare module 'redux-form/lib/__tests__/asyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/asyncValidation.spec'>;
}
declare module 'redux-form/lib/__tests__/createFieldArrayProps.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/createFieldArrayProps.spec'>;
}
declare module 'redux-form/lib/__tests__/createFieldProps.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/createFieldProps.spec'>;
}
declare module 'redux-form/lib/__tests__/defaultShouldAsyncValidate.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/defaultShouldAsyncValidate.spec'>;
}
declare module 'redux-form/lib/__tests__/defaultShouldValidate.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/defaultShouldValidate.spec'>;
}
declare module 'redux-form/lib/__tests__/deleteInWithCleanUp.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/deleteInWithCleanUp.spec'>;
}
declare module 'redux-form/lib/__tests__/Field.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/Field.spec'>;
}
declare module 'redux-form/lib/__tests__/FieldArray.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/FieldArray.spec'>;
}
declare module 'redux-form/lib/__tests__/fieldKeys.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/fieldKeys.spec'>;
}
declare module 'redux-form/lib/__tests__/Fields.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/Fields.spec'>;
}
declare module 'redux-form/lib/__tests__/Form.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/Form.spec'>;
}
declare module 'redux-form/lib/__tests__/FormSection.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/FormSection.spec'>;
}
declare module 'redux-form/lib/__tests__/formValueSelector.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/formValueSelector.spec'>;
}
declare module 'redux-form/lib/__tests__/generateFields.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/generateFields.spec'>;
}
declare module 'redux-form/lib/__tests__/generateValidator.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/generateValidator.spec'>;
}
declare module 'redux-form/lib/__tests__/handleSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/handleSubmit.spec'>;
}
declare module 'redux-form/lib/__tests__/hasError.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/hasError.spec'>;
}
declare module 'redux-form/lib/__tests__/immutable.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/immutable.spec'>;
}
declare module 'redux-form/lib/__tests__/index.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/index.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayInsert.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayInsert.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayMove.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayMove.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayPop.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayPop.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayPush.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayPush.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayRemove.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayRemove.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayRemoveAll.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayRemoveAll.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayShift.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayShift.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arraySplice.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arraySplice.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arraySwap.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arraySwap.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.arrayUnshift.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.arrayUnshift.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.autofill.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.autofill.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.blur.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.blur.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.change.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.change.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.clearAsyncError.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.clearAsyncError.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.clearSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.clearSubmit.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.clearSubmitErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.clearSubmitErrors.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.destroy.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.destroy.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.focus.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.focus.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.initialize.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.initialize.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.plugin.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.plugin.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.registerField.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.registerField.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.reset.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.reset.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.setSubmitFailed.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.setSubmitFailed.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.setSubmitSuceeded.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.setSubmitSuceeded.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.startAsyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.startAsyncValidation.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.startSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.startSubmit.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.stopAsyncValidation.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.stopAsyncValidation.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.stopSubmit.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.stopSubmit.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.submit.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.submit.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.touch.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.touch.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.unregisterField.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.unregisterField.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.untouch.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.untouch.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.updateSyncErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.updateSyncErrors.spec'>;
}
declare module 'redux-form/lib/__tests__/reducer.updateSyncWarnings.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reducer.updateSyncWarnings.spec'>;
}
declare module 'redux-form/lib/__tests__/reduxForm.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/reduxForm.spec'>;
}
declare module 'redux-form/lib/__tests__/setup.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/setup'>;
}
declare module 'redux-form/lib/__tests__/values.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/__tests__/values.spec'>;
}
declare module 'redux-form/lib/actions.js' {
  declare module.exports: $Exports<'redux-form/lib/actions'>;
}
declare module 'redux-form/lib/actionTypes.js' {
  declare module.exports: $Exports<'redux-form/lib/actionTypes'>;
}
declare module 'redux-form/lib/asyncValidation.js' {
  declare module.exports: $Exports<'redux-form/lib/asyncValidation'>;
}
declare module 'redux-form/lib/ConnectedField.js' {
  declare module.exports: $Exports<'redux-form/lib/ConnectedField'>;
}
declare module 'redux-form/lib/ConnectedFieldArray.js' {
  declare module.exports: $Exports<'redux-form/lib/ConnectedFieldArray'>;
}
declare module 'redux-form/lib/ConnectedFields.js' {
  declare module.exports: $Exports<'redux-form/lib/ConnectedFields'>;
}
declare module 'redux-form/lib/createAll.js' {
  declare module.exports: $Exports<'redux-form/lib/createAll'>;
}
declare module 'redux-form/lib/createFieldArrayProps.js' {
  declare module.exports: $Exports<'redux-form/lib/createFieldArrayProps'>;
}
declare module 'redux-form/lib/createFieldProps.js' {
  declare module.exports: $Exports<'redux-form/lib/createFieldProps'>;
}
declare module 'redux-form/lib/defaultShouldAsyncValidate.js' {
  declare module.exports: $Exports<'redux-form/lib/defaultShouldAsyncValidate'>;
}
declare module 'redux-form/lib/defaultShouldValidate.js' {
  declare module.exports: $Exports<'redux-form/lib/defaultShouldValidate'>;
}
declare module 'redux-form/lib/deleteInWithCleanUp.js' {
  declare module.exports: $Exports<'redux-form/lib/deleteInWithCleanUp'>;
}
declare module 'redux-form/lib/events/__tests__/getValue.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/getValue.spec'>;
}
declare module 'redux-form/lib/events/__tests__/isEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/isEvent.spec'>;
}
declare module 'redux-form/lib/events/__tests__/onChangeValue.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/onChangeValue.spec'>;
}
declare module 'redux-form/lib/events/__tests__/silenceEvent.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/silenceEvent.spec'>;
}
declare module 'redux-form/lib/events/__tests__/silenceEvents.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/events/__tests__/silenceEvents.spec'>;
}
declare module 'redux-form/lib/events/getValue.js' {
  declare module.exports: $Exports<'redux-form/lib/events/getValue'>;
}
declare module 'redux-form/lib/events/isEvent.js' {
  declare module.exports: $Exports<'redux-form/lib/events/isEvent'>;
}
declare module 'redux-form/lib/events/onChangeValue.js' {
  declare module.exports: $Exports<'redux-form/lib/events/onChangeValue'>;
}
declare module 'redux-form/lib/events/silenceEvent.js' {
  declare module.exports: $Exports<'redux-form/lib/events/silenceEvent'>;
}
declare module 'redux-form/lib/events/silenceEvents.js' {
  declare module.exports: $Exports<'redux-form/lib/events/silenceEvents'>;
}
declare module 'redux-form/lib/Field.js' {
  declare module.exports: $Exports<'redux-form/lib/Field'>;
}
declare module 'redux-form/lib/FieldArray.js' {
  declare module.exports: $Exports<'redux-form/lib/FieldArray'>;
}
declare module 'redux-form/lib/fieldKeys.js' {
  declare module.exports: $Exports<'redux-form/lib/fieldKeys'>;
}
declare module 'redux-form/lib/Fields.js' {
  declare module.exports: $Exports<'redux-form/lib/Fields'>;
}
declare module 'redux-form/lib/Form.js' {
  declare module.exports: $Exports<'redux-form/lib/Form'>;
}
declare module 'redux-form/lib/FormSection.js' {
  declare module.exports: $Exports<'redux-form/lib/FormSection'>;
}
declare module 'redux-form/lib/formValueSelector.js' {
  declare module.exports: $Exports<'redux-form/lib/formValueSelector'>;
}
declare module 'redux-form/lib/generateFields.js' {
  declare module.exports: $Exports<'redux-form/lib/generateFields'>;
}
declare module 'redux-form/lib/generateValidator.js' {
  declare module.exports: $Exports<'redux-form/lib/generateValidator'>;
}
declare module 'redux-form/lib/handleSubmit.js' {
  declare module.exports: $Exports<'redux-form/lib/handleSubmit'>;
}
declare module 'redux-form/lib/hasError.js' {
  declare module.exports: $Exports<'redux-form/lib/hasError'>;
}
declare module 'redux-form/lib/immutable.js' {
  declare module.exports: $Exports<'redux-form/lib/immutable'>;
}
declare module 'redux-form/lib/index.js' {
  declare module.exports: $Exports<'redux-form/lib/index'>;
}
declare module 'redux-form/lib/isChecked.js' {
  declare module.exports: $Exports<'redux-form/lib/isChecked'>;
}
declare module 'redux-form/lib/isReactNative.js' {
  declare module.exports: $Exports<'redux-form/lib/isReactNative'>;
}
declare module 'redux-form/lib/propTypes.js' {
  declare module.exports: $Exports<'redux-form/lib/propTypes'>;
}
declare module 'redux-form/lib/reducer.js' {
  declare module.exports: $Exports<'redux-form/lib/reducer'>;
}
declare module 'redux-form/lib/reduxForm.js' {
  declare module.exports: $Exports<'redux-form/lib/reduxForm'>;
}
declare module 'redux-form/lib/selectors/__tests__/getFormAsyncErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/getFormAsyncErrors.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/getFormInitialValues.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/getFormInitialValues.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/getFormNames.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/getFormNames.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/getFormSubmitErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/getFormSubmitErrors.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/getFormSyncErrors.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/getFormSyncErrors.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/getFormSyncWarnings.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/getFormSyncWarnings.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/getFormValues.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/getFormValues.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/hasSubmitFailed.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/hasSubmitFailed.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/hasSubmitSucceeded.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/hasSubmitSucceeded.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/isDirty.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/isDirty.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/isInvalid.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/isInvalid.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/isPristine.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/isPristine.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/isSubmitting.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/isSubmitting.spec'>;
}
declare module 'redux-form/lib/selectors/__tests__/isValid.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/__tests__/isValid.spec'>;
}
declare module 'redux-form/lib/selectors/getFormAsyncErrors.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/getFormAsyncErrors'>;
}
declare module 'redux-form/lib/selectors/getFormInitialValues.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/getFormInitialValues'>;
}
declare module 'redux-form/lib/selectors/getFormNames.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/getFormNames'>;
}
declare module 'redux-form/lib/selectors/getFormSubmitErrors.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/getFormSubmitErrors'>;
}
declare module 'redux-form/lib/selectors/getFormSyncErrors.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/getFormSyncErrors'>;
}
declare module 'redux-form/lib/selectors/getFormSyncWarnings.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/getFormSyncWarnings'>;
}
declare module 'redux-form/lib/selectors/getFormValues.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/getFormValues'>;
}
declare module 'redux-form/lib/selectors/hasSubmitFailed.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/hasSubmitFailed'>;
}
declare module 'redux-form/lib/selectors/hasSubmitSucceeded.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/hasSubmitSucceeded'>;
}
declare module 'redux-form/lib/selectors/isDirty.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/isDirty'>;
}
declare module 'redux-form/lib/selectors/isInvalid.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/isInvalid'>;
}
declare module 'redux-form/lib/selectors/isPristine.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/isPristine'>;
}
declare module 'redux-form/lib/selectors/isSubmitting.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/isSubmitting'>;
}
declare module 'redux-form/lib/selectors/isValid.js' {
  declare module.exports: $Exports<'redux-form/lib/selectors/isValid'>;
}
declare module 'redux-form/lib/structure/immutable/__tests__/deepEqual.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/__tests__/deepEqual.spec'>;
}
declare module 'redux-form/lib/structure/immutable/__tests__/keys.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/__tests__/keys.spec'>;
}
declare module 'redux-form/lib/structure/immutable/__tests__/setIn.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/__tests__/setIn.spec'>;
}
declare module 'redux-form/lib/structure/immutable/__tests__/splice.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/__tests__/splice.spec'>;
}
declare module 'redux-form/lib/structure/immutable/deepEqual.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/deepEqual'>;
}
declare module 'redux-form/lib/structure/immutable/expectations.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/expectations'>;
}
declare module 'redux-form/lib/structure/immutable/index.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/index'>;
}
declare module 'redux-form/lib/structure/immutable/keys.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/keys'>;
}
declare module 'redux-form/lib/structure/immutable/setIn.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/setIn'>;
}
declare module 'redux-form/lib/structure/immutable/splice.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/immutable/splice'>;
}
declare module 'redux-form/lib/structure/plain/__tests__/deepEqual.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/__tests__/deepEqual.spec'>;
}
declare module 'redux-form/lib/structure/plain/__tests__/deleteIn.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/__tests__/deleteIn.spec'>;
}
declare module 'redux-form/lib/structure/plain/__tests__/getIn.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/__tests__/getIn.spec'>;
}
declare module 'redux-form/lib/structure/plain/__tests__/keys.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/__tests__/keys.spec'>;
}
declare module 'redux-form/lib/structure/plain/__tests__/setIn.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/__tests__/setIn.spec'>;
}
declare module 'redux-form/lib/structure/plain/__tests__/splice.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/__tests__/splice.spec'>;
}
declare module 'redux-form/lib/structure/plain/deepEqual.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/deepEqual'>;
}
declare module 'redux-form/lib/structure/plain/deleteIn.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/deleteIn'>;
}
declare module 'redux-form/lib/structure/plain/expectations.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/expectations'>;
}
declare module 'redux-form/lib/structure/plain/getIn.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/getIn'>;
}
declare module 'redux-form/lib/structure/plain/index.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/index'>;
}
declare module 'redux-form/lib/structure/plain/keys.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/keys'>;
}
declare module 'redux-form/lib/structure/plain/setIn.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/setIn'>;
}
declare module 'redux-form/lib/structure/plain/splice.js' {
  declare module.exports: $Exports<'redux-form/lib/structure/plain/splice'>;
}
declare module 'redux-form/lib/SubmissionError.js' {
  declare module.exports: $Exports<'redux-form/lib/SubmissionError'>;
}
declare module 'redux-form/lib/util/__tests__/eventMocks.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/util/__tests__/eventMocks.spec'>;
}
declare module 'redux-form/lib/util/__tests__/getDisplayName.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/util/__tests__/getDisplayName.spec'>;
}
declare module 'redux-form/lib/util/__tests__/prefixName.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/util/__tests__/prefixName.spec'>;
}
declare module 'redux-form/lib/util/__tests__/shallowCompare.spec.js' {
  declare module.exports: $Exports<'redux-form/lib/util/__tests__/shallowCompare.spec'>;
}
declare module 'redux-form/lib/util/eventConsts.js' {
  declare module.exports: $Exports<'redux-form/lib/util/eventConsts'>;
}
declare module 'redux-form/lib/util/eventMocks.js' {
  declare module.exports: $Exports<'redux-form/lib/util/eventMocks'>;
}
declare module 'redux-form/lib/util/getDisplayName.js' {
  declare module.exports: $Exports<'redux-form/lib/util/getDisplayName'>;
}
declare module 'redux-form/lib/util/prefixName.js' {
  declare module.exports: $Exports<'redux-form/lib/util/prefixName'>;
}
declare module 'redux-form/lib/util/shallowCompare.js' {
  declare module.exports: $Exports<'redux-form/lib/util/shallowCompare'>;
}
declare module 'redux-form/lib/values.js' {
  declare module.exports: $Exports<'redux-form/lib/values'>;
}
