// flow-typed signature: f121384c4100880518b0ce66fda824c5
// flow-typed version: <<STUB>>/stylus_v0.54.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylus/lib/browserify' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/fs' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/memory' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/null' {
  declare module.exports: any;
}

declare module 'stylus/lib/colors' {
  declare module.exports: any;
}

declare module 'stylus/lib/convert/css' {
  declare module.exports: any;
}

declare module 'stylus/lib/errors' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/add-property' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/adjust' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/alpha' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/base-convert' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/basename' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/blend' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/blue' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/clone' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/component' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/contrast' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/convert' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/current-media' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/define' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/dirname' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/error' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/extname' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/green' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/hsl' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/hsla' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/hue' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/image-size' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/image' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/json' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/length' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/lightness' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/list-separator' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/lookup' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/luminosity' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/match' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/math-prop' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/math' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/merge' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/operate' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/opposite-position' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/p' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/pathjoin' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/pop' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/prefix-classes' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/push' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/range' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/red' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/remove' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/replace' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/resolver' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/rgb' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/rgba' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/s' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/saturation' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/selector-exists' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/selector' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/selectors' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/shift' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/slice' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/split' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/substr' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/tan' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/trace' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/transparentify' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/type' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/unit' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/unquote' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/unshift' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/url' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/use' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/warn' {
  declare module.exports: any;
}

declare module 'stylus/lib/lexer' {
  declare module.exports: any;
}

declare module 'stylus/lib/middleware' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/arguments' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/atblock' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/atrule' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/binop' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/block' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/boolean' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/call' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/charset' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/comment' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/each' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/expression' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/extend' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/feature' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/function' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/group' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/hsla' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/ident' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/if' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/import' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/keyframes' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/literal' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/media' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/member' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/namespace' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/node' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/null' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/object' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/params' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/property' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/query-list' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/query' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/return' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/rgba' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/root' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/selector' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/string' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/supports' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/ternary' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/unaryop' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/unit' {
  declare module.exports: any;
}

declare module 'stylus/lib/parser' {
  declare module.exports: any;
}

declare module 'stylus/lib/renderer' {
  declare module.exports: any;
}

declare module 'stylus/lib/selector-parser' {
  declare module.exports: any;
}

declare module 'stylus/lib/stack/frame' {
  declare module.exports: any;
}

declare module 'stylus/lib/stack/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/stack/scope' {
  declare module.exports: any;
}

declare module 'stylus/lib/stylus' {
  declare module.exports: any;
}

declare module 'stylus/lib/token' {
  declare module.exports: any;
}

declare module 'stylus/lib/units' {
  declare module.exports: any;
}

declare module 'stylus/lib/utils' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/compiler' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/deps-resolver' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/evaluator' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/normalizer' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/sourcemapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylus/index' {
  declare module.exports: $Exports<'stylus'>;
}
declare module 'stylus/index.js' {
  declare module.exports: $Exports<'stylus'>;
}
declare module 'stylus/lib/browserify.js' {
  declare module.exports: $Exports<'stylus/lib/browserify'>;
}
declare module 'stylus/lib/cache/fs.js' {
  declare module.exports: $Exports<'stylus/lib/cache/fs'>;
}
declare module 'stylus/lib/cache/index.js' {
  declare module.exports: $Exports<'stylus/lib/cache/index'>;
}
declare module 'stylus/lib/cache/memory.js' {
  declare module.exports: $Exports<'stylus/lib/cache/memory'>;
}
declare module 'stylus/lib/cache/null.js' {
  declare module.exports: $Exports<'stylus/lib/cache/null'>;
}
declare module 'stylus/lib/colors.js' {
  declare module.exports: $Exports<'stylus/lib/colors'>;
}
declare module 'stylus/lib/convert/css.js' {
  declare module.exports: $Exports<'stylus/lib/convert/css'>;
}
declare module 'stylus/lib/errors.js' {
  declare module.exports: $Exports<'stylus/lib/errors'>;
}
declare module 'stylus/lib/functions/add-property.js' {
  declare module.exports: $Exports<'stylus/lib/functions/add-property'>;
}
declare module 'stylus/lib/functions/adjust.js' {
  declare module.exports: $Exports<'stylus/lib/functions/adjust'>;
}
declare module 'stylus/lib/functions/alpha.js' {
  declare module.exports: $Exports<'stylus/lib/functions/alpha'>;
}
declare module 'stylus/lib/functions/base-convert.js' {
  declare module.exports: $Exports<'stylus/lib/functions/base-convert'>;
}
declare module 'stylus/lib/functions/basename.js' {
  declare module.exports: $Exports<'stylus/lib/functions/basename'>;
}
declare module 'stylus/lib/functions/blend.js' {
  declare module.exports: $Exports<'stylus/lib/functions/blend'>;
}
declare module 'stylus/lib/functions/blue.js' {
  declare module.exports: $Exports<'stylus/lib/functions/blue'>;
}
declare module 'stylus/lib/functions/clone.js' {
  declare module.exports: $Exports<'stylus/lib/functions/clone'>;
}
declare module 'stylus/lib/functions/component.js' {
  declare module.exports: $Exports<'stylus/lib/functions/component'>;
}
declare module 'stylus/lib/functions/contrast.js' {
  declare module.exports: $Exports<'stylus/lib/functions/contrast'>;
}
declare module 'stylus/lib/functions/convert.js' {
  declare module.exports: $Exports<'stylus/lib/functions/convert'>;
}
declare module 'stylus/lib/functions/current-media.js' {
  declare module.exports: $Exports<'stylus/lib/functions/current-media'>;
}
declare module 'stylus/lib/functions/define.js' {
  declare module.exports: $Exports<'stylus/lib/functions/define'>;
}
declare module 'stylus/lib/functions/dirname.js' {
  declare module.exports: $Exports<'stylus/lib/functions/dirname'>;
}
declare module 'stylus/lib/functions/error.js' {
  declare module.exports: $Exports<'stylus/lib/functions/error'>;
}
declare module 'stylus/lib/functions/extname.js' {
  declare module.exports: $Exports<'stylus/lib/functions/extname'>;
}
declare module 'stylus/lib/functions/green.js' {
  declare module.exports: $Exports<'stylus/lib/functions/green'>;
}
declare module 'stylus/lib/functions/hsl.js' {
  declare module.exports: $Exports<'stylus/lib/functions/hsl'>;
}
declare module 'stylus/lib/functions/hsla.js' {
  declare module.exports: $Exports<'stylus/lib/functions/hsla'>;
}
declare module 'stylus/lib/functions/hue.js' {
  declare module.exports: $Exports<'stylus/lib/functions/hue'>;
}
declare module 'stylus/lib/functions/image-size.js' {
  declare module.exports: $Exports<'stylus/lib/functions/image-size'>;
}
declare module 'stylus/lib/functions/image.js' {
  declare module.exports: $Exports<'stylus/lib/functions/image'>;
}
declare module 'stylus/lib/functions/index.js' {
  declare module.exports: $Exports<'stylus/lib/functions/index'>;
}
declare module 'stylus/lib/functions/json.js' {
  declare module.exports: $Exports<'stylus/lib/functions/json'>;
}
declare module 'stylus/lib/functions/length.js' {
  declare module.exports: $Exports<'stylus/lib/functions/length'>;
}
declare module 'stylus/lib/functions/lightness.js' {
  declare module.exports: $Exports<'stylus/lib/functions/lightness'>;
}
declare module 'stylus/lib/functions/list-separator.js' {
  declare module.exports: $Exports<'stylus/lib/functions/list-separator'>;
}
declare module 'stylus/lib/functions/lookup.js' {
  declare module.exports: $Exports<'stylus/lib/functions/lookup'>;
}
declare module 'stylus/lib/functions/luminosity.js' {
  declare module.exports: $Exports<'stylus/lib/functions/luminosity'>;
}
declare module 'stylus/lib/functions/match.js' {
  declare module.exports: $Exports<'stylus/lib/functions/match'>;
}
declare module 'stylus/lib/functions/math-prop.js' {
  declare module.exports: $Exports<'stylus/lib/functions/math-prop'>;
}
declare module 'stylus/lib/functions/math.js' {
  declare module.exports: $Exports<'stylus/lib/functions/math'>;
}
declare module 'stylus/lib/functions/merge.js' {
  declare module.exports: $Exports<'stylus/lib/functions/merge'>;
}
declare module 'stylus/lib/functions/operate.js' {
  declare module.exports: $Exports<'stylus/lib/functions/operate'>;
}
declare module 'stylus/lib/functions/opposite-position.js' {
  declare module.exports: $Exports<'stylus/lib/functions/opposite-position'>;
}
declare module 'stylus/lib/functions/p.js' {
  declare module.exports: $Exports<'stylus/lib/functions/p'>;
}
declare module 'stylus/lib/functions/pathjoin.js' {
  declare module.exports: $Exports<'stylus/lib/functions/pathjoin'>;
}
declare module 'stylus/lib/functions/pop.js' {
  declare module.exports: $Exports<'stylus/lib/functions/pop'>;
}
declare module 'stylus/lib/functions/prefix-classes.js' {
  declare module.exports: $Exports<'stylus/lib/functions/prefix-classes'>;
}
declare module 'stylus/lib/functions/push.js' {
  declare module.exports: $Exports<'stylus/lib/functions/push'>;
}
declare module 'stylus/lib/functions/range.js' {
  declare module.exports: $Exports<'stylus/lib/functions/range'>;
}
declare module 'stylus/lib/functions/red.js' {
  declare module.exports: $Exports<'stylus/lib/functions/red'>;
}
declare module 'stylus/lib/functions/remove.js' {
  declare module.exports: $Exports<'stylus/lib/functions/remove'>;
}
declare module 'stylus/lib/functions/replace.js' {
  declare module.exports: $Exports<'stylus/lib/functions/replace'>;
}
declare module 'stylus/lib/functions/resolver.js' {
  declare module.exports: $Exports<'stylus/lib/functions/resolver'>;
}
declare module 'stylus/lib/functions/rgb.js' {
  declare module.exports: $Exports<'stylus/lib/functions/rgb'>;
}
declare module 'stylus/lib/functions/rgba.js' {
  declare module.exports: $Exports<'stylus/lib/functions/rgba'>;
}
declare module 'stylus/lib/functions/s.js' {
  declare module.exports: $Exports<'stylus/lib/functions/s'>;
}
declare module 'stylus/lib/functions/saturation.js' {
  declare module.exports: $Exports<'stylus/lib/functions/saturation'>;
}
declare module 'stylus/lib/functions/selector-exists.js' {
  declare module.exports: $Exports<'stylus/lib/functions/selector-exists'>;
}
declare module 'stylus/lib/functions/selector.js' {
  declare module.exports: $Exports<'stylus/lib/functions/selector'>;
}
declare module 'stylus/lib/functions/selectors.js' {
  declare module.exports: $Exports<'stylus/lib/functions/selectors'>;
}
declare module 'stylus/lib/functions/shift.js' {
  declare module.exports: $Exports<'stylus/lib/functions/shift'>;
}
declare module 'stylus/lib/functions/slice.js' {
  declare module.exports: $Exports<'stylus/lib/functions/slice'>;
}
declare module 'stylus/lib/functions/split.js' {
  declare module.exports: $Exports<'stylus/lib/functions/split'>;
}
declare module 'stylus/lib/functions/substr.js' {
  declare module.exports: $Exports<'stylus/lib/functions/substr'>;
}
declare module 'stylus/lib/functions/tan.js' {
  declare module.exports: $Exports<'stylus/lib/functions/tan'>;
}
declare module 'stylus/lib/functions/trace.js' {
  declare module.exports: $Exports<'stylus/lib/functions/trace'>;
}
declare module 'stylus/lib/functions/transparentify.js' {
  declare module.exports: $Exports<'stylus/lib/functions/transparentify'>;
}
declare module 'stylus/lib/functions/type.js' {
  declare module.exports: $Exports<'stylus/lib/functions/type'>;
}
declare module 'stylus/lib/functions/unit.js' {
  declare module.exports: $Exports<'stylus/lib/functions/unit'>;
}
declare module 'stylus/lib/functions/unquote.js' {
  declare module.exports: $Exports<'stylus/lib/functions/unquote'>;
}
declare module 'stylus/lib/functions/unshift.js' {
  declare module.exports: $Exports<'stylus/lib/functions/unshift'>;
}
declare module 'stylus/lib/functions/url.js' {
  declare module.exports: $Exports<'stylus/lib/functions/url'>;
}
declare module 'stylus/lib/functions/use.js' {
  declare module.exports: $Exports<'stylus/lib/functions/use'>;
}
declare module 'stylus/lib/functions/warn.js' {
  declare module.exports: $Exports<'stylus/lib/functions/warn'>;
}
declare module 'stylus/lib/lexer.js' {
  declare module.exports: $Exports<'stylus/lib/lexer'>;
}
declare module 'stylus/lib/middleware.js' {
  declare module.exports: $Exports<'stylus/lib/middleware'>;
}
declare module 'stylus/lib/nodes/arguments.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/arguments'>;
}
declare module 'stylus/lib/nodes/atblock.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/atblock'>;
}
declare module 'stylus/lib/nodes/atrule.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/atrule'>;
}
declare module 'stylus/lib/nodes/binop.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/binop'>;
}
declare module 'stylus/lib/nodes/block.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/block'>;
}
declare module 'stylus/lib/nodes/boolean.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/boolean'>;
}
declare module 'stylus/lib/nodes/call.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/call'>;
}
declare module 'stylus/lib/nodes/charset.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/charset'>;
}
declare module 'stylus/lib/nodes/comment.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/comment'>;
}
declare module 'stylus/lib/nodes/each.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/each'>;
}
declare module 'stylus/lib/nodes/expression.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/expression'>;
}
declare module 'stylus/lib/nodes/extend.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/extend'>;
}
declare module 'stylus/lib/nodes/feature.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/feature'>;
}
declare module 'stylus/lib/nodes/function.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/function'>;
}
declare module 'stylus/lib/nodes/group.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/group'>;
}
declare module 'stylus/lib/nodes/hsla.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/hsla'>;
}
declare module 'stylus/lib/nodes/ident.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/ident'>;
}
declare module 'stylus/lib/nodes/if.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/if'>;
}
declare module 'stylus/lib/nodes/import.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/import'>;
}
declare module 'stylus/lib/nodes/index.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/index'>;
}
declare module 'stylus/lib/nodes/keyframes.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/keyframes'>;
}
declare module 'stylus/lib/nodes/literal.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/literal'>;
}
declare module 'stylus/lib/nodes/media.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/media'>;
}
declare module 'stylus/lib/nodes/member.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/member'>;
}
declare module 'stylus/lib/nodes/namespace.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/namespace'>;
}
declare module 'stylus/lib/nodes/node.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/node'>;
}
declare module 'stylus/lib/nodes/null.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/null'>;
}
declare module 'stylus/lib/nodes/object.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/object'>;
}
declare module 'stylus/lib/nodes/params.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/params'>;
}
declare module 'stylus/lib/nodes/property.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/property'>;
}
declare module 'stylus/lib/nodes/query-list.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/query-list'>;
}
declare module 'stylus/lib/nodes/query.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/query'>;
}
declare module 'stylus/lib/nodes/return.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/return'>;
}
declare module 'stylus/lib/nodes/rgba.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/rgba'>;
}
declare module 'stylus/lib/nodes/root.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/root'>;
}
declare module 'stylus/lib/nodes/selector.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/selector'>;
}
declare module 'stylus/lib/nodes/string.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/string'>;
}
declare module 'stylus/lib/nodes/supports.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/supports'>;
}
declare module 'stylus/lib/nodes/ternary.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/ternary'>;
}
declare module 'stylus/lib/nodes/unaryop.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/unaryop'>;
}
declare module 'stylus/lib/nodes/unit.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/unit'>;
}
declare module 'stylus/lib/parser.js' {
  declare module.exports: $Exports<'stylus/lib/parser'>;
}
declare module 'stylus/lib/renderer.js' {
  declare module.exports: $Exports<'stylus/lib/renderer'>;
}
declare module 'stylus/lib/selector-parser.js' {
  declare module.exports: $Exports<'stylus/lib/selector-parser'>;
}
declare module 'stylus/lib/stack/frame.js' {
  declare module.exports: $Exports<'stylus/lib/stack/frame'>;
}
declare module 'stylus/lib/stack/index.js' {
  declare module.exports: $Exports<'stylus/lib/stack/index'>;
}
declare module 'stylus/lib/stack/scope.js' {
  declare module.exports: $Exports<'stylus/lib/stack/scope'>;
}
declare module 'stylus/lib/stylus.js' {
  declare module.exports: $Exports<'stylus/lib/stylus'>;
}
declare module 'stylus/lib/token.js' {
  declare module.exports: $Exports<'stylus/lib/token'>;
}
declare module 'stylus/lib/units.js' {
  declare module.exports: $Exports<'stylus/lib/units'>;
}
declare module 'stylus/lib/utils.js' {
  declare module.exports: $Exports<'stylus/lib/utils'>;
}
declare module 'stylus/lib/visitor/compiler.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/compiler'>;
}
declare module 'stylus/lib/visitor/deps-resolver.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/deps-resolver'>;
}
declare module 'stylus/lib/visitor/evaluator.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/evaluator'>;
}
declare module 'stylus/lib/visitor/index.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/index'>;
}
declare module 'stylus/lib/visitor/normalizer.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/normalizer'>;
}
declare module 'stylus/lib/visitor/sourcemapper.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/sourcemapper'>;
}
