// flow-typed signature: fe539d278edfe599d68e129352ec2b16
// flow-typed version: <<STUB>>/stylint_v1.5.9/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylint/src/checks/blocks' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/brackets' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/colons' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/colors' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/commaSpace' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/commentSpace' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/cssLiteral' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/depthLimit' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/duplicates' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/efficient' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/extendPref' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/indentPref' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/index' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/leadingZero' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/mixed' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/namingConvention' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/noImportant' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/none' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/parenSpace' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/placeholders' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/prefixVarsWithDollar' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/quotePref' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/semicolons' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/sortOrder' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/stackedProperties' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/trailingWhitespace' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/universal' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/valid' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/zeroUnits' {
  declare module.exports: any;
}

declare module 'stylint/src/checks/zIndexNormalize' {
  declare module.exports: any;
}

declare module 'stylint/src/core/cache' {
  declare module.exports: any;
}

declare module 'stylint/src/core/config' {
  declare module.exports: any;
}

declare module 'stylint/src/core/done' {
  declare module.exports: any;
}

declare module 'stylint/src/core/index' {
  declare module.exports: any;
}

declare module 'stylint/src/core/init' {
  declare module.exports: any;
}

declare module 'stylint/src/core/lint' {
  declare module.exports: any;
}

declare module 'stylint/src/core/parse' {
  declare module.exports: any;
}

declare module 'stylint/src/core/read' {
  declare module.exports: any;
}

declare module 'stylint/src/core/reporter' {
  declare module.exports: any;
}

declare module 'stylint/src/core/setState' {
  declare module.exports: any;
}

declare module 'stylint/src/core/state' {
  declare module.exports: any;
}

declare module 'stylint/src/core/watch' {
  declare module.exports: any;
}

declare module 'stylint/src/state/hashOrCSSEnd' {
  declare module.exports: any;
}

declare module 'stylint/src/state/hashOrCSSStart' {
  declare module.exports: any;
}

declare module 'stylint/src/state/index' {
  declare module.exports: any;
}

declare module 'stylint/src/state/keyframesEnd' {
  declare module.exports: any;
}

declare module 'stylint/src/state/keyframesStart' {
  declare module.exports: any;
}

declare module 'stylint/src/state/rootEnd' {
  declare module.exports: any;
}

declare module 'stylint/src/state/rootStart' {
  declare module.exports: any;
}

declare module 'stylint/src/state/startsWithComment' {
  declare module.exports: any;
}

declare module 'stylint/src/state/stylintOff' {
  declare module.exports: any;
}

declare module 'stylint/src/state/stylintOn' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/checkPrefix' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/checkPseudo' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/getFiles' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/msg' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/resetOnChange' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/setConfig' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/setContext' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/splitAndStrip' {
  declare module.exports: any;
}

declare module 'stylint/src/utils/trimLine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylint/index' {
  declare module.exports: $Exports<'stylint'>;
}
declare module 'stylint/index.js' {
  declare module.exports: $Exports<'stylint'>;
}
declare module 'stylint/src/checks/blocks.js' {
  declare module.exports: $Exports<'stylint/src/checks/blocks'>;
}
declare module 'stylint/src/checks/brackets.js' {
  declare module.exports: $Exports<'stylint/src/checks/brackets'>;
}
declare module 'stylint/src/checks/colons.js' {
  declare module.exports: $Exports<'stylint/src/checks/colons'>;
}
declare module 'stylint/src/checks/colors.js' {
  declare module.exports: $Exports<'stylint/src/checks/colors'>;
}
declare module 'stylint/src/checks/commaSpace.js' {
  declare module.exports: $Exports<'stylint/src/checks/commaSpace'>;
}
declare module 'stylint/src/checks/commentSpace.js' {
  declare module.exports: $Exports<'stylint/src/checks/commentSpace'>;
}
declare module 'stylint/src/checks/cssLiteral.js' {
  declare module.exports: $Exports<'stylint/src/checks/cssLiteral'>;
}
declare module 'stylint/src/checks/depthLimit.js' {
  declare module.exports: $Exports<'stylint/src/checks/depthLimit'>;
}
declare module 'stylint/src/checks/duplicates.js' {
  declare module.exports: $Exports<'stylint/src/checks/duplicates'>;
}
declare module 'stylint/src/checks/efficient.js' {
  declare module.exports: $Exports<'stylint/src/checks/efficient'>;
}
declare module 'stylint/src/checks/extendPref.js' {
  declare module.exports: $Exports<'stylint/src/checks/extendPref'>;
}
declare module 'stylint/src/checks/indentPref.js' {
  declare module.exports: $Exports<'stylint/src/checks/indentPref'>;
}
declare module 'stylint/src/checks/index.js' {
  declare module.exports: $Exports<'stylint/src/checks/index'>;
}
declare module 'stylint/src/checks/leadingZero.js' {
  declare module.exports: $Exports<'stylint/src/checks/leadingZero'>;
}
declare module 'stylint/src/checks/mixed.js' {
  declare module.exports: $Exports<'stylint/src/checks/mixed'>;
}
declare module 'stylint/src/checks/namingConvention.js' {
  declare module.exports: $Exports<'stylint/src/checks/namingConvention'>;
}
declare module 'stylint/src/checks/noImportant.js' {
  declare module.exports: $Exports<'stylint/src/checks/noImportant'>;
}
declare module 'stylint/src/checks/none.js' {
  declare module.exports: $Exports<'stylint/src/checks/none'>;
}
declare module 'stylint/src/checks/parenSpace.js' {
  declare module.exports: $Exports<'stylint/src/checks/parenSpace'>;
}
declare module 'stylint/src/checks/placeholders.js' {
  declare module.exports: $Exports<'stylint/src/checks/placeholders'>;
}
declare module 'stylint/src/checks/prefixVarsWithDollar.js' {
  declare module.exports: $Exports<'stylint/src/checks/prefixVarsWithDollar'>;
}
declare module 'stylint/src/checks/quotePref.js' {
  declare module.exports: $Exports<'stylint/src/checks/quotePref'>;
}
declare module 'stylint/src/checks/semicolons.js' {
  declare module.exports: $Exports<'stylint/src/checks/semicolons'>;
}
declare module 'stylint/src/checks/sortOrder.js' {
  declare module.exports: $Exports<'stylint/src/checks/sortOrder'>;
}
declare module 'stylint/src/checks/stackedProperties.js' {
  declare module.exports: $Exports<'stylint/src/checks/stackedProperties'>;
}
declare module 'stylint/src/checks/trailingWhitespace.js' {
  declare module.exports: $Exports<'stylint/src/checks/trailingWhitespace'>;
}
declare module 'stylint/src/checks/universal.js' {
  declare module.exports: $Exports<'stylint/src/checks/universal'>;
}
declare module 'stylint/src/checks/valid.js' {
  declare module.exports: $Exports<'stylint/src/checks/valid'>;
}
declare module 'stylint/src/checks/zeroUnits.js' {
  declare module.exports: $Exports<'stylint/src/checks/zeroUnits'>;
}
declare module 'stylint/src/checks/zIndexNormalize.js' {
  declare module.exports: $Exports<'stylint/src/checks/zIndexNormalize'>;
}
declare module 'stylint/src/core/cache.js' {
  declare module.exports: $Exports<'stylint/src/core/cache'>;
}
declare module 'stylint/src/core/config.js' {
  declare module.exports: $Exports<'stylint/src/core/config'>;
}
declare module 'stylint/src/core/done.js' {
  declare module.exports: $Exports<'stylint/src/core/done'>;
}
declare module 'stylint/src/core/index.js' {
  declare module.exports: $Exports<'stylint/src/core/index'>;
}
declare module 'stylint/src/core/init.js' {
  declare module.exports: $Exports<'stylint/src/core/init'>;
}
declare module 'stylint/src/core/lint.js' {
  declare module.exports: $Exports<'stylint/src/core/lint'>;
}
declare module 'stylint/src/core/parse.js' {
  declare module.exports: $Exports<'stylint/src/core/parse'>;
}
declare module 'stylint/src/core/read.js' {
  declare module.exports: $Exports<'stylint/src/core/read'>;
}
declare module 'stylint/src/core/reporter.js' {
  declare module.exports: $Exports<'stylint/src/core/reporter'>;
}
declare module 'stylint/src/core/setState.js' {
  declare module.exports: $Exports<'stylint/src/core/setState'>;
}
declare module 'stylint/src/core/state.js' {
  declare module.exports: $Exports<'stylint/src/core/state'>;
}
declare module 'stylint/src/core/watch.js' {
  declare module.exports: $Exports<'stylint/src/core/watch'>;
}
declare module 'stylint/src/state/hashOrCSSEnd.js' {
  declare module.exports: $Exports<'stylint/src/state/hashOrCSSEnd'>;
}
declare module 'stylint/src/state/hashOrCSSStart.js' {
  declare module.exports: $Exports<'stylint/src/state/hashOrCSSStart'>;
}
declare module 'stylint/src/state/index.js' {
  declare module.exports: $Exports<'stylint/src/state/index'>;
}
declare module 'stylint/src/state/keyframesEnd.js' {
  declare module.exports: $Exports<'stylint/src/state/keyframesEnd'>;
}
declare module 'stylint/src/state/keyframesStart.js' {
  declare module.exports: $Exports<'stylint/src/state/keyframesStart'>;
}
declare module 'stylint/src/state/rootEnd.js' {
  declare module.exports: $Exports<'stylint/src/state/rootEnd'>;
}
declare module 'stylint/src/state/rootStart.js' {
  declare module.exports: $Exports<'stylint/src/state/rootStart'>;
}
declare module 'stylint/src/state/startsWithComment.js' {
  declare module.exports: $Exports<'stylint/src/state/startsWithComment'>;
}
declare module 'stylint/src/state/stylintOff.js' {
  declare module.exports: $Exports<'stylint/src/state/stylintOff'>;
}
declare module 'stylint/src/state/stylintOn.js' {
  declare module.exports: $Exports<'stylint/src/state/stylintOn'>;
}
declare module 'stylint/src/utils/checkPrefix.js' {
  declare module.exports: $Exports<'stylint/src/utils/checkPrefix'>;
}
declare module 'stylint/src/utils/checkPseudo.js' {
  declare module.exports: $Exports<'stylint/src/utils/checkPseudo'>;
}
declare module 'stylint/src/utils/getFiles.js' {
  declare module.exports: $Exports<'stylint/src/utils/getFiles'>;
}
declare module 'stylint/src/utils/msg.js' {
  declare module.exports: $Exports<'stylint/src/utils/msg'>;
}
declare module 'stylint/src/utils/resetOnChange.js' {
  declare module.exports: $Exports<'stylint/src/utils/resetOnChange'>;
}
declare module 'stylint/src/utils/setConfig.js' {
  declare module.exports: $Exports<'stylint/src/utils/setConfig'>;
}
declare module 'stylint/src/utils/setContext.js' {
  declare module.exports: $Exports<'stylint/src/utils/setContext'>;
}
declare module 'stylint/src/utils/splitAndStrip.js' {
  declare module.exports: $Exports<'stylint/src/utils/splitAndStrip'>;
}
declare module 'stylint/src/utils/trimLine.js' {
  declare module.exports: $Exports<'stylint/src/utils/trimLine'>;
}
