// flow-typed signature: 2bcea6efe28880b54f717568da2a20b1
// flow-typed version: <<STUB>>/stylus-loader_v3.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylus-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylus-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylus-loader/lib/evaluator' {
  declare module.exports: any;
}

declare module 'stylus-loader/lib/listimports' {
  declare module.exports: any;
}

declare module 'stylus-loader/lib/pathcache' {
  declare module.exports: any;
}

declare module 'stylus-loader/lib/resolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylus-loader/index' {
  declare module.exports: $Exports<'stylus-loader'>;
}
declare module 'stylus-loader/index.js' {
  declare module.exports: $Exports<'stylus-loader'>;
}
declare module 'stylus-loader/lib/evaluator.js' {
  declare module.exports: $Exports<'stylus-loader/lib/evaluator'>;
}
declare module 'stylus-loader/lib/listimports.js' {
  declare module.exports: $Exports<'stylus-loader/lib/listimports'>;
}
declare module 'stylus-loader/lib/pathcache.js' {
  declare module.exports: $Exports<'stylus-loader/lib/pathcache'>;
}
declare module 'stylus-loader/lib/resolver.js' {
  declare module.exports: $Exports<'stylus-loader/lib/resolver'>;
}
