// flow-typed signature: c13490798aed1a7de8695efc58208d05
// flow-typed version: <<STUB>>/whatwg-fetch_v2.0.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'whatwg-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'whatwg-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'whatwg-fetch/fetch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'whatwg-fetch/fetch.js' {
  declare module.exports: $Exports<'whatwg-fetch/fetch'>;
}
