import Head from 'next/head'

export default function SectionNamePage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <input name="name" />
      </main>
    </div>
  )
}
