import { useCallback, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Preview } from '../../components/generator/Preview'

export default function SectionNamePage() {
  const [url, setUrl] = useState('/blank.pdf')
  const router = useRouter()
  const sectionName = router.query.sectionName as string

  // eslint-disable-next-line no-console
  console.log(sectionName)

  const handleSubmit = useCallback(() => {
    const input = document.querySelector('input') as HTMLInputElement
    const name = input.value

    fetch('/api/resume/pdf', {
      method: 'POST',
      body: JSON.stringify({ name }),
      headers: {
        Accept: 'application/pdf'
      }
    })
      .then((response) => {
        return response.blob()
      })
      .then((blob) => {
        const newUrl = URL.createObjectURL(blob)
        setUrl(newUrl)
      })
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <input name="name" />
        <button type="button" onClick={handleSubmit}>
          BASICS PAGE
        </button>
        <Preview url={url} />
      </main>
    </div>
  )
}
