const CLEAR_SCHOOL_FIELD = 'CLEAR_SCHOOL_FIELD'
const CLEAR_JOB_FIELD = 'CLEAR_JOB_FIELD'
const CLEAR_JOB_DUTY_FIELD = 'CLEAR_JOB_DUTY_FIELD'
const CLEAR_PROJECT_FIELD = 'CLEAR_PROJECT_FIELD'
const CLEAR_SKILL_FIELD = 'CLEAR_SKILL_FIELD'
const CLEAR_AWARD_FIELD = 'CLEAR_AWARD_FIELD'

export {
  CLEAR_SCHOOL_FIELD,
  CLEAR_JOB_FIELD,
  CLEAR_JOB_DUTY_FIELD,
  CLEAR_PROJECT_FIELD,
  CLEAR_SKILL_FIELD,
  CLEAR_AWARD_FIELD
}
