const SELECT_TEMPLATE = 'SELECT_TEMPLATE'
const REQUEST_RESUME = 'REQUEST_RESUME'
const RECEIVE_RESUME = 'RECEIVE_RESUME'
const SAVE_RESUME_DATA = 'SAVE_RESUME_DATA'
const REQUEST_SOURCE = 'REQUEST_SOURCE'
const RECEIVE_SOURCE = 'RECEIVE_SOURCE'
const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES'
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
const PREV_PAGE = 'PREV_PAGE'
const NEXT_PAGE = 'NEXT_PAGE'

export {
  SELECT_TEMPLATE,
  REQUEST_RESUME,
  RECEIVE_RESUME,
  SAVE_RESUME_DATA,
  REQUEST_SOURCE,
  RECEIVE_SOURCE,
  SET_TOTAL_PAGES,
  SET_CURRENT_PAGE,
  PREV_PAGE,
  NEXT_PAGE
}
