const SELECT_TEMPLATE = 'SELECT_TEMPLATE'
const REQUEST_RESUME = 'REQUEST_RESUME'
const RESUME_SUCCESS = 'RESUME_SUCCESS'
const RESUME_FAILURE = 'RESUME_FAILURE'
const SAVE_RESUME_DATA = 'SAVE_RESUME_DATA'
const REQUEST_SOURCE = 'REQUEST_SOURCE'
const RECEIVE_SOURCE = 'RECEIVE_SOURCE'
const SET_PAGE_COUNT = 'SET_PAGE_COUNT'
const SET_PAGE = 'SET_PAGE'
const PREV_PAGE = 'PREV_PAGE'
const NEXT_PAGE = 'NEXT_PAGE'

export {
  SELECT_TEMPLATE,
  REQUEST_RESUME,
  RESUME_SUCCESS,
  RESUME_FAILURE,
  SAVE_RESUME_DATA,
  REQUEST_SOURCE,
  RECEIVE_SOURCE,
  SET_PAGE_COUNT,
  SET_PAGE,
  PREV_PAGE,
  NEXT_PAGE
}
