const SELECT_TEMPLATE = 'SELECT_TEMPLATE'
const REQUEST_RESUME = 'REQUEST_RESUME'
const RECEIVE_RESUME = 'RECEIVE_RESUME'
const SAVE_PREVIOUS_RESUME = 'SAVE_PREVIOUS_RESUME'
const REQUEST_SOURCE = 'REQUEST_SOURCE'
const RECEIVE_SOURCE = 'RECEIVE_SOURCE'
const SET_PAGE_COUNT = 'SET_PAGE_COUNT'
const SET_PAGE = 'SET_PAGE'
const PREV_PAGE = 'PREV_PAGE'
const NEXT_PAGE = 'NEXT_PAGE'

export {
  SELECT_TEMPLATE,
  REQUEST_RESUME,
  RECEIVE_RESUME,
  SAVE_PREVIOUS_RESUME,
  REQUEST_SOURCE,
  RECEIVE_SOURCE,
  SET_PAGE_COUNT,
  SET_PAGE,
  PREV_PAGE,
  NEXT_PAGE
}
