const SELECT_TEMPLATE = 'SELECT_TEMPLATE'
const ADD_SCHOOL = 'ADD_SCHOOL'
const REMOVE_SCHOOL = 'REMOVE_SCHOOL'
const ADD_JOB = 'ADD_JOB'
const REMOVE_JOB = 'REMOVE_JOB'
const INCREMENT_JOB_DUTY = 'INCREMENT_JOB_DUTY'
const DECREMENT_JOB_DUTY = 'DECREMENT_JOB_DUTY'
const ADD_PROJECT = 'ADD_PROJECT'
const REMOVE_PROJECT = 'REMOVE_PROJECT'
const ADD_SKILL = 'ADD_SKILL'
const REMOVE_SKILL = 'REMOVE_SKILL'
const SET_RESUME_URL = 'SET_RESUME_URL'

export {
  SELECT_TEMPLATE,
  ADD_SCHOOL,
  REMOVE_SCHOOL,
  ADD_JOB,
  REMOVE_JOB,
  INCREMENT_JOB_DUTY,
  DECREMENT_JOB_DUTY,
  ADD_PROJECT,
  REMOVE_PROJECT,
  ADD_SKILL,
  REMOVE_SKILL,
  SET_RESUME_URL
}
