const SELECT_TEMPLATE = 'SELECT_TEMPLATE'
const ADD_SCHOOL = 'ADD_SCHOOL'
const REMOVE_SCHOOL = 'REMOVE_SCHOOL'
const ADD_JOB = 'ADD_JOB'
const REMOVE_JOB = 'REMOVE_JOB'
const INCREMENT_JOB_DUTY = 'INCREMENT_JOB_DUTY'
const DECREMENT_JOB_DUTY = 'DECREMENT_JOB_DUTY'
const ADD_PROJECT = 'ADD_PROJECT'
const REMOVE_PROJECT = 'REMOVE_PROJECT'
const ADD_SKILL = 'ADD_SKILL'
const REMOVE_SKILL = 'REMOVE_SKILL'
const REQUEST_RESUME = 'REQUEST_RESUME'
const RECEIVE_RESUME = 'RECEIVE_RESUME'
const SAVE_PREVIOUS_RESUME = 'SAVE_PREVIOUS_RESUME'

export {
  SELECT_TEMPLATE,
  ADD_SCHOOL,
  REMOVE_SCHOOL,
  ADD_JOB,
  REMOVE_JOB,
  INCREMENT_JOB_DUTY,
  DECREMENT_JOB_DUTY,
  ADD_PROJECT,
  REMOVE_PROJECT,
  ADD_SKILL,
  REMOVE_SKILL,
  REQUEST_RESUME,
  RECEIVE_RESUME,
  SAVE_PREVIOUS_RESUME
}
