const SHOW_MODAL = 'SHOW_MODAL'
const HIDE_MODAL = 'HIDE_MODAL'
const SHOW_SIDE_NAV = 'SHOW_SIDE_NAV'
const HIDE_SIDE_NAV = 'HIDE_SIDE_NAV'
const ADD_SCHOOL = 'ADD_SCHOOL'
const REMOVE_SCHOOL = 'REMOVE_SCHOOL'
const ADD_JOB = 'ADD_JOB'
const REMOVE_JOB = 'REMOVE_JOB'
const INCREMENT_JOB_DUTY = 'INCREMENT_JOB_DUTY'
const DECREMENT_JOB_DUTY = 'DECREMENT_JOB_DUTY'
const ADD_PROJECT = 'ADD_PROJECT'
const REMOVE_PROJECT = 'REMOVE_PROJECT'
const ADD_SKILL = 'ADD_SKILL'
const REMOVE_SKILL = 'REMOVE_SKILL'

export {
  SHOW_MODAL,
  HIDE_MODAL,
  SHOW_SIDE_NAV,
  HIDE_SIDE_NAV,
  ADD_SCHOOL,
  REMOVE_SCHOOL,
  ADD_JOB,
  REMOVE_JOB,
  INCREMENT_JOB_DUTY,
  DECREMENT_JOB_DUTY,
  ADD_PROJECT,
  REMOVE_PROJECT,
  ADD_SKILL,
  REMOVE_SKILL
}
