const SHOW_MODAL = 'SHOW_MODAL'
const HIDE_MODAL = 'HIDE_MODAL'
const SHOW_SIDE_NAV = 'SHOW_SIDE_NAV'
const HIDE_SIDE_NAV = 'HIDE_SIDE_NAV'

export {
  SHOW_MODAL,
  HIDE_MODAL,
  SHOW_SIDE_NAV,
  HIDE_SIDE_NAV
}
