const TEMPLATE1 = 1
const TEMPLATE2 = 2
const TEMPLATE3 = 3
const TEMPLATE4 = 4
const TEMPLATE5 = 5
const TEMPLATE6 = 6
const TEMPLATE7 = 7

module.exports = {
  TEMPLATE1,
  TEMPLATE2,
  TEMPLATE3,
  TEMPLATE4,
  TEMPLATE5,
  TEMPLATE6,
  TEMPLATE7
}
