// flow-typed signature: e4064d843915847252e5b9c86bf44051
// flow-typed version: <<STUB>>/archiver_v1.3.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'archiver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'archiver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'archiver/lib/core' {
  declare module.exports: any;
}

declare module 'archiver/lib/plugins/json' {
  declare module.exports: any;
}

declare module 'archiver/lib/plugins/tar' {
  declare module.exports: any;
}

declare module 'archiver/lib/plugins/zip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'archiver/index' {
  declare module.exports: $Exports<'archiver'>;
}
declare module 'archiver/index.js' {
  declare module.exports: $Exports<'archiver'>;
}
declare module 'archiver/lib/core.js' {
  declare module.exports: $Exports<'archiver/lib/core'>;
}
declare module 'archiver/lib/plugins/json.js' {
  declare module.exports: $Exports<'archiver/lib/plugins/json'>;
}
declare module 'archiver/lib/plugins/tar.js' {
  declare module.exports: $Exports<'archiver/lib/plugins/tar'>;
}
declare module 'archiver/lib/plugins/zip.js' {
  declare module.exports: $Exports<'archiver/lib/plugins/zip'>;
}
