// flow-typed signature: f36d53f8d6119e86bfcdc7756a17c2b8
// flow-typed version: <<STUB>>/blyss_v^9.0.7/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blyss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blyss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blyss/bin/blyss' {
  declare module.exports: any;
}

declare module 'blyss/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blyss/bin/blyss.js' {
  declare module.exports: $Exports<'blyss/bin/blyss'>;
}
declare module 'blyss/index' {
  declare module.exports: $Exports<'blyss'>;
}
declare module 'blyss/index.js' {
  declare module.exports: $Exports<'blyss'>;
}
declare module 'blyss/options.js' {
  declare module.exports: $Exports<'blyss/options'>;
}
