// flow-typed signature: 3dea19847680e4dd8c33f45bbbba689b
// flow-typed version: <<STUB>>/common-tags_v^1.4.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'common-tags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'common-tags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'common-tags/es/codeBlock/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/commaLists/commaLists' {
  declare module.exports: any;
}

declare module 'common-tags/es/commaLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/commaListsAnd/commaListsAnd' {
  declare module.exports: any;
}

declare module 'common-tags/es/commaListsAnd/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/commaListsOr/commaListsOr' {
  declare module.exports: any;
}

declare module 'common-tags/es/commaListsOr/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/html/html' {
  declare module.exports: any;
}

declare module 'common-tags/es/html/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/inlineArrayTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/inlineArrayTransformer/inlineArrayTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/es/inlineLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/inlineLists/inlineLists' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLine/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLine/oneLine' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineCommaLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineCommaLists/oneLineCommaLists' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineCommaListsAnd/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineCommaListsAnd/oneLineCommaListsAnd' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineCommaListsOr/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineCommaListsOr/oneLineCommaListsOr' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineInlineLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineInlineLists/oneLineInlineLists' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineTrim/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/oneLineTrim/oneLineTrim' {
  declare module.exports: any;
}

declare module 'common-tags/es/removeNonPrintingValuesTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/removeNonPrintingValuesTransformer/removeNonPrintingValuesTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/es/replaceResultTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/replaceResultTransformer/replaceResultTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/es/replaceSubstitutionTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/replaceSubstitutionTransformer/replaceSubstitutionTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/es/safeHtml/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/safeHtml/safeHtml' {
  declare module.exports: any;
}

declare module 'common-tags/es/source/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/splitStringTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/splitStringTransformer/splitStringTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/es/stripIndent/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/stripIndent/stripIndent' {
  declare module.exports: any;
}

declare module 'common-tags/es/stripIndents/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/stripIndents/stripIndents' {
  declare module.exports: any;
}

declare module 'common-tags/es/stripIndentTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/stripIndentTransformer/stripIndentTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/es/TemplateTag/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/TemplateTag/TemplateTag' {
  declare module.exports: any;
}

declare module 'common-tags/es/trimResultTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/trimResultTransformer/trimResultTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/es/utils/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/utils/readFromFixture/index' {
  declare module.exports: any;
}

declare module 'common-tags/es/utils/readFromFixture/readFromFixture' {
  declare module.exports: any;
}

declare module 'common-tags/lib/codeBlock/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/commaLists/commaLists' {
  declare module.exports: any;
}

declare module 'common-tags/lib/commaLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/commaListsAnd/commaListsAnd' {
  declare module.exports: any;
}

declare module 'common-tags/lib/commaListsAnd/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/commaListsOr/commaListsOr' {
  declare module.exports: any;
}

declare module 'common-tags/lib/commaListsOr/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/html/html' {
  declare module.exports: any;
}

declare module 'common-tags/lib/html/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/inlineArrayTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/inlineArrayTransformer/inlineArrayTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/lib/inlineLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/inlineLists/inlineLists' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLine/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLine/oneLine' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineCommaLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineCommaLists/oneLineCommaLists' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineCommaListsAnd/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineCommaListsAnd/oneLineCommaListsAnd' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineCommaListsOr/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineCommaListsOr/oneLineCommaListsOr' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineInlineLists/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineInlineLists/oneLineInlineLists' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineTrim/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/oneLineTrim/oneLineTrim' {
  declare module.exports: any;
}

declare module 'common-tags/lib/removeNonPrintingValuesTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/removeNonPrintingValuesTransformer/removeNonPrintingValuesTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/lib/replaceResultTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/replaceResultTransformer/replaceResultTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/lib/replaceSubstitutionTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/replaceSubstitutionTransformer/replaceSubstitutionTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/lib/safeHtml/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/safeHtml/safeHtml' {
  declare module.exports: any;
}

declare module 'common-tags/lib/source/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/splitStringTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/splitStringTransformer/splitStringTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/lib/stripIndent/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/stripIndent/stripIndent' {
  declare module.exports: any;
}

declare module 'common-tags/lib/stripIndents/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/stripIndents/stripIndents' {
  declare module.exports: any;
}

declare module 'common-tags/lib/stripIndentTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/stripIndentTransformer/stripIndentTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/lib/TemplateTag/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/TemplateTag/TemplateTag' {
  declare module.exports: any;
}

declare module 'common-tags/lib/trimResultTransformer/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/trimResultTransformer/trimResultTransformer' {
  declare module.exports: any;
}

declare module 'common-tags/lib/utils/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/utils/readFromFixture/index' {
  declare module.exports: any;
}

declare module 'common-tags/lib/utils/readFromFixture/readFromFixture' {
  declare module.exports: any;
}

// Filename aliases
declare module 'common-tags/es/codeBlock/index.js' {
  declare module.exports: $Exports<'common-tags/es/codeBlock/index'>;
}
declare module 'common-tags/es/commaLists/commaLists.js' {
  declare module.exports: $Exports<'common-tags/es/commaLists/commaLists'>;
}
declare module 'common-tags/es/commaLists/index.js' {
  declare module.exports: $Exports<'common-tags/es/commaLists/index'>;
}
declare module 'common-tags/es/commaListsAnd/commaListsAnd.js' {
  declare module.exports: $Exports<'common-tags/es/commaListsAnd/commaListsAnd'>;
}
declare module 'common-tags/es/commaListsAnd/index.js' {
  declare module.exports: $Exports<'common-tags/es/commaListsAnd/index'>;
}
declare module 'common-tags/es/commaListsOr/commaListsOr.js' {
  declare module.exports: $Exports<'common-tags/es/commaListsOr/commaListsOr'>;
}
declare module 'common-tags/es/commaListsOr/index.js' {
  declare module.exports: $Exports<'common-tags/es/commaListsOr/index'>;
}
declare module 'common-tags/es/html/html.js' {
  declare module.exports: $Exports<'common-tags/es/html/html'>;
}
declare module 'common-tags/es/html/index.js' {
  declare module.exports: $Exports<'common-tags/es/html/index'>;
}
declare module 'common-tags/es/index.js' {
  declare module.exports: $Exports<'common-tags/es/index'>;
}
declare module 'common-tags/es/inlineArrayTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/es/inlineArrayTransformer/index'>;
}
declare module 'common-tags/es/inlineArrayTransformer/inlineArrayTransformer.js' {
  declare module.exports: $Exports<'common-tags/es/inlineArrayTransformer/inlineArrayTransformer'>;
}
declare module 'common-tags/es/inlineLists/index.js' {
  declare module.exports: $Exports<'common-tags/es/inlineLists/index'>;
}
declare module 'common-tags/es/inlineLists/inlineLists.js' {
  declare module.exports: $Exports<'common-tags/es/inlineLists/inlineLists'>;
}
declare module 'common-tags/es/oneLine/index.js' {
  declare module.exports: $Exports<'common-tags/es/oneLine/index'>;
}
declare module 'common-tags/es/oneLine/oneLine.js' {
  declare module.exports: $Exports<'common-tags/es/oneLine/oneLine'>;
}
declare module 'common-tags/es/oneLineCommaLists/index.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineCommaLists/index'>;
}
declare module 'common-tags/es/oneLineCommaLists/oneLineCommaLists.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineCommaLists/oneLineCommaLists'>;
}
declare module 'common-tags/es/oneLineCommaListsAnd/index.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineCommaListsAnd/index'>;
}
declare module 'common-tags/es/oneLineCommaListsAnd/oneLineCommaListsAnd.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineCommaListsAnd/oneLineCommaListsAnd'>;
}
declare module 'common-tags/es/oneLineCommaListsOr/index.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineCommaListsOr/index'>;
}
declare module 'common-tags/es/oneLineCommaListsOr/oneLineCommaListsOr.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineCommaListsOr/oneLineCommaListsOr'>;
}
declare module 'common-tags/es/oneLineInlineLists/index.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineInlineLists/index'>;
}
declare module 'common-tags/es/oneLineInlineLists/oneLineInlineLists.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineInlineLists/oneLineInlineLists'>;
}
declare module 'common-tags/es/oneLineTrim/index.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineTrim/index'>;
}
declare module 'common-tags/es/oneLineTrim/oneLineTrim.js' {
  declare module.exports: $Exports<'common-tags/es/oneLineTrim/oneLineTrim'>;
}
declare module 'common-tags/es/removeNonPrintingValuesTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/es/removeNonPrintingValuesTransformer/index'>;
}
declare module 'common-tags/es/removeNonPrintingValuesTransformer/removeNonPrintingValuesTransformer.js' {
  declare module.exports: $Exports<'common-tags/es/removeNonPrintingValuesTransformer/removeNonPrintingValuesTransformer'>;
}
declare module 'common-tags/es/replaceResultTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/es/replaceResultTransformer/index'>;
}
declare module 'common-tags/es/replaceResultTransformer/replaceResultTransformer.js' {
  declare module.exports: $Exports<'common-tags/es/replaceResultTransformer/replaceResultTransformer'>;
}
declare module 'common-tags/es/replaceSubstitutionTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/es/replaceSubstitutionTransformer/index'>;
}
declare module 'common-tags/es/replaceSubstitutionTransformer/replaceSubstitutionTransformer.js' {
  declare module.exports: $Exports<'common-tags/es/replaceSubstitutionTransformer/replaceSubstitutionTransformer'>;
}
declare module 'common-tags/es/safeHtml/index.js' {
  declare module.exports: $Exports<'common-tags/es/safeHtml/index'>;
}
declare module 'common-tags/es/safeHtml/safeHtml.js' {
  declare module.exports: $Exports<'common-tags/es/safeHtml/safeHtml'>;
}
declare module 'common-tags/es/source/index.js' {
  declare module.exports: $Exports<'common-tags/es/source/index'>;
}
declare module 'common-tags/es/splitStringTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/es/splitStringTransformer/index'>;
}
declare module 'common-tags/es/splitStringTransformer/splitStringTransformer.js' {
  declare module.exports: $Exports<'common-tags/es/splitStringTransformer/splitStringTransformer'>;
}
declare module 'common-tags/es/stripIndent/index.js' {
  declare module.exports: $Exports<'common-tags/es/stripIndent/index'>;
}
declare module 'common-tags/es/stripIndent/stripIndent.js' {
  declare module.exports: $Exports<'common-tags/es/stripIndent/stripIndent'>;
}
declare module 'common-tags/es/stripIndents/index.js' {
  declare module.exports: $Exports<'common-tags/es/stripIndents/index'>;
}
declare module 'common-tags/es/stripIndents/stripIndents.js' {
  declare module.exports: $Exports<'common-tags/es/stripIndents/stripIndents'>;
}
declare module 'common-tags/es/stripIndentTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/es/stripIndentTransformer/index'>;
}
declare module 'common-tags/es/stripIndentTransformer/stripIndentTransformer.js' {
  declare module.exports: $Exports<'common-tags/es/stripIndentTransformer/stripIndentTransformer'>;
}
declare module 'common-tags/es/TemplateTag/index.js' {
  declare module.exports: $Exports<'common-tags/es/TemplateTag/index'>;
}
declare module 'common-tags/es/TemplateTag/TemplateTag.js' {
  declare module.exports: $Exports<'common-tags/es/TemplateTag/TemplateTag'>;
}
declare module 'common-tags/es/trimResultTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/es/trimResultTransformer/index'>;
}
declare module 'common-tags/es/trimResultTransformer/trimResultTransformer.js' {
  declare module.exports: $Exports<'common-tags/es/trimResultTransformer/trimResultTransformer'>;
}
declare module 'common-tags/es/utils/index.js' {
  declare module.exports: $Exports<'common-tags/es/utils/index'>;
}
declare module 'common-tags/es/utils/readFromFixture/index.js' {
  declare module.exports: $Exports<'common-tags/es/utils/readFromFixture/index'>;
}
declare module 'common-tags/es/utils/readFromFixture/readFromFixture.js' {
  declare module.exports: $Exports<'common-tags/es/utils/readFromFixture/readFromFixture'>;
}
declare module 'common-tags/lib/codeBlock/index.js' {
  declare module.exports: $Exports<'common-tags/lib/codeBlock/index'>;
}
declare module 'common-tags/lib/commaLists/commaLists.js' {
  declare module.exports: $Exports<'common-tags/lib/commaLists/commaLists'>;
}
declare module 'common-tags/lib/commaLists/index.js' {
  declare module.exports: $Exports<'common-tags/lib/commaLists/index'>;
}
declare module 'common-tags/lib/commaListsAnd/commaListsAnd.js' {
  declare module.exports: $Exports<'common-tags/lib/commaListsAnd/commaListsAnd'>;
}
declare module 'common-tags/lib/commaListsAnd/index.js' {
  declare module.exports: $Exports<'common-tags/lib/commaListsAnd/index'>;
}
declare module 'common-tags/lib/commaListsOr/commaListsOr.js' {
  declare module.exports: $Exports<'common-tags/lib/commaListsOr/commaListsOr'>;
}
declare module 'common-tags/lib/commaListsOr/index.js' {
  declare module.exports: $Exports<'common-tags/lib/commaListsOr/index'>;
}
declare module 'common-tags/lib/html/html.js' {
  declare module.exports: $Exports<'common-tags/lib/html/html'>;
}
declare module 'common-tags/lib/html/index.js' {
  declare module.exports: $Exports<'common-tags/lib/html/index'>;
}
declare module 'common-tags/lib/index.js' {
  declare module.exports: $Exports<'common-tags/lib/index'>;
}
declare module 'common-tags/lib/inlineArrayTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/lib/inlineArrayTransformer/index'>;
}
declare module 'common-tags/lib/inlineArrayTransformer/inlineArrayTransformer.js' {
  declare module.exports: $Exports<'common-tags/lib/inlineArrayTransformer/inlineArrayTransformer'>;
}
declare module 'common-tags/lib/inlineLists/index.js' {
  declare module.exports: $Exports<'common-tags/lib/inlineLists/index'>;
}
declare module 'common-tags/lib/inlineLists/inlineLists.js' {
  declare module.exports: $Exports<'common-tags/lib/inlineLists/inlineLists'>;
}
declare module 'common-tags/lib/oneLine/index.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLine/index'>;
}
declare module 'common-tags/lib/oneLine/oneLine.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLine/oneLine'>;
}
declare module 'common-tags/lib/oneLineCommaLists/index.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineCommaLists/index'>;
}
declare module 'common-tags/lib/oneLineCommaLists/oneLineCommaLists.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineCommaLists/oneLineCommaLists'>;
}
declare module 'common-tags/lib/oneLineCommaListsAnd/index.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineCommaListsAnd/index'>;
}
declare module 'common-tags/lib/oneLineCommaListsAnd/oneLineCommaListsAnd.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineCommaListsAnd/oneLineCommaListsAnd'>;
}
declare module 'common-tags/lib/oneLineCommaListsOr/index.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineCommaListsOr/index'>;
}
declare module 'common-tags/lib/oneLineCommaListsOr/oneLineCommaListsOr.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineCommaListsOr/oneLineCommaListsOr'>;
}
declare module 'common-tags/lib/oneLineInlineLists/index.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineInlineLists/index'>;
}
declare module 'common-tags/lib/oneLineInlineLists/oneLineInlineLists.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineInlineLists/oneLineInlineLists'>;
}
declare module 'common-tags/lib/oneLineTrim/index.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineTrim/index'>;
}
declare module 'common-tags/lib/oneLineTrim/oneLineTrim.js' {
  declare module.exports: $Exports<'common-tags/lib/oneLineTrim/oneLineTrim'>;
}
declare module 'common-tags/lib/removeNonPrintingValuesTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/lib/removeNonPrintingValuesTransformer/index'>;
}
declare module 'common-tags/lib/removeNonPrintingValuesTransformer/removeNonPrintingValuesTransformer.js' {
  declare module.exports: $Exports<'common-tags/lib/removeNonPrintingValuesTransformer/removeNonPrintingValuesTransformer'>;
}
declare module 'common-tags/lib/replaceResultTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/lib/replaceResultTransformer/index'>;
}
declare module 'common-tags/lib/replaceResultTransformer/replaceResultTransformer.js' {
  declare module.exports: $Exports<'common-tags/lib/replaceResultTransformer/replaceResultTransformer'>;
}
declare module 'common-tags/lib/replaceSubstitutionTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/lib/replaceSubstitutionTransformer/index'>;
}
declare module 'common-tags/lib/replaceSubstitutionTransformer/replaceSubstitutionTransformer.js' {
  declare module.exports: $Exports<'common-tags/lib/replaceSubstitutionTransformer/replaceSubstitutionTransformer'>;
}
declare module 'common-tags/lib/safeHtml/index.js' {
  declare module.exports: $Exports<'common-tags/lib/safeHtml/index'>;
}
declare module 'common-tags/lib/safeHtml/safeHtml.js' {
  declare module.exports: $Exports<'common-tags/lib/safeHtml/safeHtml'>;
}
declare module 'common-tags/lib/source/index.js' {
  declare module.exports: $Exports<'common-tags/lib/source/index'>;
}
declare module 'common-tags/lib/splitStringTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/lib/splitStringTransformer/index'>;
}
declare module 'common-tags/lib/splitStringTransformer/splitStringTransformer.js' {
  declare module.exports: $Exports<'common-tags/lib/splitStringTransformer/splitStringTransformer'>;
}
declare module 'common-tags/lib/stripIndent/index.js' {
  declare module.exports: $Exports<'common-tags/lib/stripIndent/index'>;
}
declare module 'common-tags/lib/stripIndent/stripIndent.js' {
  declare module.exports: $Exports<'common-tags/lib/stripIndent/stripIndent'>;
}
declare module 'common-tags/lib/stripIndents/index.js' {
  declare module.exports: $Exports<'common-tags/lib/stripIndents/index'>;
}
declare module 'common-tags/lib/stripIndents/stripIndents.js' {
  declare module.exports: $Exports<'common-tags/lib/stripIndents/stripIndents'>;
}
declare module 'common-tags/lib/stripIndentTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/lib/stripIndentTransformer/index'>;
}
declare module 'common-tags/lib/stripIndentTransformer/stripIndentTransformer.js' {
  declare module.exports: $Exports<'common-tags/lib/stripIndentTransformer/stripIndentTransformer'>;
}
declare module 'common-tags/lib/TemplateTag/index.js' {
  declare module.exports: $Exports<'common-tags/lib/TemplateTag/index'>;
}
declare module 'common-tags/lib/TemplateTag/TemplateTag.js' {
  declare module.exports: $Exports<'common-tags/lib/TemplateTag/TemplateTag'>;
}
declare module 'common-tags/lib/trimResultTransformer/index.js' {
  declare module.exports: $Exports<'common-tags/lib/trimResultTransformer/index'>;
}
declare module 'common-tags/lib/trimResultTransformer/trimResultTransformer.js' {
  declare module.exports: $Exports<'common-tags/lib/trimResultTransformer/trimResultTransformer'>;
}
declare module 'common-tags/lib/utils/index.js' {
  declare module.exports: $Exports<'common-tags/lib/utils/index'>;
}
declare module 'common-tags/lib/utils/readFromFixture/index.js' {
  declare module.exports: $Exports<'common-tags/lib/utils/readFromFixture/index'>;
}
declare module 'common-tags/lib/utils/readFromFixture/readFromFixture.js' {
  declare module.exports: $Exports<'common-tags/lib/utils/readFromFixture/readFromFixture'>;
}
