// flow-typed signature: 2e8cd1f2e3eed4451adde0a4db49c71d
// flow-typed version: <<STUB>>/fs-promise_v^2.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-promise/test/basic' {
  declare module.exports: any;
}

declare module 'fs-promise/test/mz' {
  declare module.exports: any;
}

declare module 'fs-promise/test/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-promise/index' {
  declare module.exports: $Exports<'fs-promise'>;
}
declare module 'fs-promise/index.js' {
  declare module.exports: $Exports<'fs-promise'>;
}
declare module 'fs-promise/test/basic.js' {
  declare module.exports: $Exports<'fs-promise/test/basic'>;
}
declare module 'fs-promise/test/mz.js' {
  declare module.exports: $Exports<'fs-promise/test/mz'>;
}
declare module 'fs-promise/test/register.js' {
  declare module.exports: $Exports<'fs-promise/test/register'>;
}
