// flow-typed signature: db7b01afe7fc19c4d2557c9dbe13afc8
// flow-typed version: <<STUB>>/koa-static_v^4.0.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-static/index' {
  declare module.exports: $Exports<'koa-static'>;
}
declare module 'koa-static/index.js' {
  declare module.exports: $Exports<'koa-static'>;
}
