// flow-typed signature: 1027120fd8580615a6b59b5b58206f7a
// flow-typed version: <<STUB>>/koa-bodyparser_v^4.2.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-bodyparser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-bodyparser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-bodyparser/index' {
  declare module.exports: $Exports<'koa-bodyparser'>;
}
declare module 'koa-bodyparser/index.js' {
  declare module.exports: $Exports<'koa-bodyparser'>;
}
