// flow-typed signature: f0ecf09835ebc5f7d78b14bba29498e8
// flow-typed version: <<STUB>>/koa2-formidable_v^1.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa2-formidable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa2-formidable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa2-formidable/index' {
  declare module.exports: $Exports<'koa2-formidable'>;
}
declare module 'koa2-formidable/index.js' {
  declare module.exports: $Exports<'koa2-formidable'>;
}
