// flow-typed signature: 3a49e38e2c0d8dfbc0c5e3975eb12e15
// flow-typed version: <<STUB>>/node-latex_v^2.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-latex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-latex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-latex/examples/error-logs/index' {
  declare module.exports: any;
}

declare module 'node-latex/examples/simple/index' {
  declare module.exports: any;
}

declare module 'node-latex/examples/with-cls/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-latex/examples/error-logs/index.js' {
  declare module.exports: $Exports<'node-latex/examples/error-logs/index'>;
}
declare module 'node-latex/examples/simple/index.js' {
  declare module.exports: $Exports<'node-latex/examples/simple/index'>;
}
declare module 'node-latex/examples/with-cls/index.js' {
  declare module.exports: $Exports<'node-latex/examples/with-cls/index'>;
}
declare module 'node-latex/index' {
  declare module.exports: $Exports<'node-latex'>;
}
declare module 'node-latex/index.js' {
  declare module.exports: $Exports<'node-latex'>;
}
