// flow-typed signature: 6799700fe422f4a6e09e2c78e311c482
// flow-typed version: <<STUB>>/pretty-latex_v0.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-latex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-latex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pretty-latex/index' {
  declare module.exports: $Exports<'pretty-latex'>;
}
declare module 'pretty-latex/index.js' {
  declare module.exports: $Exports<'pretty-latex'>;
}
