// flow-typed signature: 40cf6584efa4a11cefe9358b59804244
// flow-typed version: <<STUB>>/sanitize-latex_v0.1.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize-latex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize-latex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sanitize-latex/index' {
  declare module.exports: $Exports<'sanitize-latex'>;
}
declare module 'sanitize-latex/index.js' {
  declare module.exports: $Exports<'sanitize-latex'>;
}
