// flow-typed signature: f318ddaaeb48bafb252900b39e911a66
// flow-typed version: <<STUB>>/bulma-stylus_v0.4.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-stylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-stylus' {
  declare module.exports: any;
}
