// flow-typed signature: 853879981d130f9ce49db9c1fcd614ea
// flow-typed version: <<STUB>>/react-image-lightbox_v^4.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-lightbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-lightbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-lightbox/dist/umd/react-image-lightbox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-lightbox/dist/umd/react-image-lightbox.js' {
  declare module.exports: $Exports<'react-image-lightbox/dist/umd/react-image-lightbox'>;
}
