// flow-typed signature: 88cdc69befe4ccd2485ba24accd86723
// flow-typed version: <<STUB>>/stylint-loader_v1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylint-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylint-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylint-loader/index' {
  declare module.exports: $Exports<'stylint-loader'>;
}
declare module 'stylint-loader/index.js' {
  declare module.exports: $Exports<'stylint-loader'>;
}
